### DISCUSSION TITLE
How does Karpenter handle node unresponsiveness in cases like OOMs?

### DISCUSSION THREAD

**Discussion by The9thLime** [kubernetes-sigs/karpenter#2186] [Q&A]
Hey. I have a nodepool spec like this

 ```
spec:
   disruption:
     budgets:
       - nodes: 10%
       - nodes: 0%
         reasons:
           - Drifted
     consolidateAfter: 30m
     consolidationPolicy: WhenEmptyOrUnderutilized
   limits:
     cpu: '60'
   template:
     spec:
       expireAfter: 720h
       nodeClassRef:
         group: karpenter.k8s.aws
         kind: EC2NodeClass
         name: mimir
       requirements:
         - key: topology.kubernetes.io/zone
           operator: In
           values:
             - us-east-1b
         - key: karpenter.sh/capacity-type
           operator: In
           values:
             - on-demand
         - key: node.kubernetes.io/instance-type
           operator: In
           values:
             - r6g.xlarge
             - r6a.xlarge
             - r5a.xlarge
       taints:
         - effect: NoSchedule
           key: kind
           value: mimir-ingesters
```

Once, all the three nodes in this NodePool became unready and unresponsive because of OOM. They stopped responding and the pods on the node got stuck in a terminating stage. Karpenter was not able to terminate those nodes (and the NodeClaims) and was not unable to provision new replacements. On the AWS console, I could see that those instances were in the terminating stage.

I was wondering how Karpenter handles these node-level OOMs since when something like this happens, the nodes become unresponsive and get into a zombie like state.
