### DISCUSSION TITLE
EC2 metadataOption default value in NodeClasses

### DISCUSSION THREAD

**Discussion by justpalma** [kubernetes-sigs/karpenter#2194] [Q&A]
Hi,
recently we decide to upgrade our karpenter installation on a EKS cluster(1.31). 
We upgrade from Karpenter 0.23 to 1.2.
Every went fine expect for one small issue.
Our pods are running on Larpenter nodes and make requests to S3. After the upgrade, we started receiving errors of "AccessDenied" on S3.
After some troubleshooting we find out that the default value of spec.metadataOptions has changed from
```yaml
#Karpenter v0.23
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
```
to
```yaml
#Karpenter v1.2
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
```
However AWS docs recommend using a bigger hop limit when using containers(EKS or ECS): https://aws.amazon.com/it/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/

![immagine](https://github.com/user-attachments/assets/c0eb3123-db44-42e2-a1e8-160f1f883924)

We resolve our problem by changing the httpPutResponseHopLimit to 2, but we still do not understand why Karpenter set this value to 1 when AWS recommends a bigger value if you use containers.
So, are we missing something? Are these default values the desired one?

Thanks
Alessandro
