### DISCUSSION TITLE
Is it possible to use Karpenter for EKS "Unmanaged Node group"

### DISCUSSION THREAD

**Discussion by phanthaihuan** [kubernetes-sigs/karpenter#529] [Q&A]
Hi forks,

I have read documentation about Karpenter:

https://karpenter.sh/docs/getting-started/

https://eksctl.io/usage/eksctl-karpenter/

as well as reading some source code:

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-with-karpenter
  region: us-west-2
  version: '1.24'
  tags:
    karpenter.sh/discovery: cluster-with-karpenter # here, it is set to the cluster name
iam:
  withOIDC: true # required

karpenter:
  version: 'v0.20.0' # Exact version must be specified

managedNodeGroups:
  - name: managed-ng-1
    minSize: 1
    maxSize: 2
    desiredCapacity: 1

```

And I think it is impossible to use Karpenter for EKS **Unmanaged** Node Group?

May I know you comments?

Best regards,
Huan
