### ISSUE TITLE
NodePool - only partly schedule and duration rule

### ISSUE THREAD

**Issue by wotolom** [kubernetes-sigs/karpenter#1003]
### Description

**Observed Behavior**:

This x-validation-rule https://github.com/kubernetes-sigs/karpenter/blob/0ac0ff583d940681c205d21617f4443035e293ac/pkg/apis/crds/karpenter.sh_nodepools.yaml#L112
seems to only work if there is only one budget with duration or schedule. As soon as there is at least one budget/entry with a correct schedule+duration set, other budgets/entries can be set with only one of the fields.

I would propose: `rule: 'self.all(x, has(x.schedule) == has(x.duration))'`

**Expected Behavior** + **Reproduction Steps** (Please include YAML):
this example should fail, but it doesn't:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: test
spec:
  # ...
  disruption:
    budgets:
    - nodes: "5"
      duration: 100m
    - nodes: "0"
      schedule: "@daily"
      duration: 10m
```

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
