### ISSUE TITLE
Karpenter can't add new nodes after a Windows workload

### ISSUE THREAD

**Issue by lightcast-cdedels** [kubernetes-sigs/karpenter#1009]
### Description

**Observed Behavior**:
On a cluster with both Windows and Linux support, no Linux nodes can be created after windows nodes have been created.

**Expected Behavior**:
Windows and Linux workloads can run at any time and at the same time.

**Reproduction Steps** (Please include YAML):
With a new EKS 1.28 cluster, perform the following steps:
1. Enable windows support by applying the following yaml (see https://docs.aws.amazon.com/eks/latest/userguide/windows-support.html):
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: amazon-vpc-cni
  namespace: kube-system
data:
  enable-windows-ipam: "true"
```
2. Install karpenter
3. Add a NodeClass for Linux
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: linux-default
spec:
  amiFamily: AL2
  role: XXX
  securityGroupSelectorTerms:
  - id: XXX
  - id: XXX
  subnetSelectorTerms:
  - id: XXX
  - id: XXX
```
4. Add a NodePool for Linux
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        name: linux-default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
  weight: 20
```
5. Add a NodeClass for Windows 
```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: windows-default
spec:
  amiFamily: Windows2022
  role: XXX
  securityGroupSelectorTerms:
  - id: XXX
  - id: XXX
  subnetSelectorTerms:
  - id: XXX
  - id: XXX
```
6. Add a NodePool for Windows 
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: windows-default
spec:
  template:
    spec:
      nodeClassRef:
        name: windows-default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - windows
  weight: 10
```
7. Add a Windows workload.  Wait until the Node is ready and the workload is running before proceeding to the next step.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-windows-deployment
  labels:
    app: eks-sample-windows-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-sample-windows-app
  template:
    metadata:
      labels:
        app: eks-sample-windows-app
    spec:
      containers:
      - name: windows-server-iis
        image: mcr.microsoft.com/windows/servercore:ltsc2022
        imagePullPolicy: IfNotPresent
        command:
        - powershell.exe
        - -command
        - "Add-WindowsFeature Web-Server; Invoke-WebRequest -UseBasicParsing -Uri 'https://dotnetbinaries.blob.core.windows.net/servicemonitor/2.0.1.6/ServiceMonitor.exe' -OutFile 'C:\\ServiceMonitor.exe'; echo '<html><body><br/><br/><marquee><H1>Hello EKS!!!<H1><marquee></body><html>' > C:\\inetpub\\wwwroot\\default.html; C:\\ServiceMonitor.exe 'w3svc'; "
      nodeSelector:
        kubernetes.io/os: windows
```
8. Add a Linux workload (I add resources to make sure karpenter adds a node to my cluster)
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:latest
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "8Gi"
            cpu: "2000m"
          limits:
            memory: "8Gi"
            cpu: "2000m"
      nodeSelector:
        kubernetes.io/os: linux
```
The expected result is that karpenter will add a new Linux node for the additional pods requested in step 8.  Instead Karpenter shows the following message:
```
{
  "level": "ERROR",
  "time": "2024-02-15T01:06:29.649Z",
  "logger": "controller.provisioner",
  "message": "Could not schedule pod, incompatible with nodepool \"default\", daemonset overhead={\"cpu\":\"660m\",\"memory\":\"1424Mi\",\"pods\":\"8\",\"vpc.amazonaws.com/PrivateIPv4Address\":\"1\"}, no instance type satisfied resources {\"cpu\":\"2660m\",\"memory\":\"9616Mi\",\"pods\":\"9\",\"vpc.amazonaws.com/PrivateIPv4Address\":\"1\"} and requirements karpenter.sh/nodepool In [default], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux] (no instance type has enough resources); incompatible with nodepool \"windows-default\", daemonset overhead={\"cpu\":\"30m\",\"memory\":\"120Mi\",\"pods\":\"1\",\"vpc.amazonaws.com/PrivateIPv4Address\":\"1\"}, incompatible requirements, key kubernetes.io/os, kubernetes.io/os In [linux] not in kubernetes.io/os In [windows]",
  "commit": "1072d3b",
  "pod": "default/eks-sample-linux-deployment-7bcbb64cc8-skgrc"
```

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
