### ISSUE TITLE
Karpenter and kube-scheduler Hangs for ~5m when Deleting a StatefulSet PVC

### ISSUE THREAD

**Issue by jonathan-innis** [kubernetes-sigs/karpenter#1029]
### Description

**Observed Behavior**:

I'm testing the behavior of #1018 and validating how Karpenter handles node rolling when the [Node Cleanup Controller](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/blob/master/docs/node-cleanup-controller.md) is responsible for deleting PVCs and PVs from a node that is using NVME storage. The behavior that I'm seeing is that Karpenter  is rolling the pods onto the new nodes, but when the new nodes come up, it takes the node cleanup controller a little bit of time to fully delete the PVCs/PVs from the old node (since it's doing the cleanup on a poll). 

When it finally does delete the PVCs, Karpenter begins reporting the following error: `"ignoring pod, getting persistent volume claim \"www-web-1\", PersistentVolumeClaim \"www-web-1\" not found"`. It does so correctly and should do so until the pod gets a replacement PVC from the stateful set controller. However, once the PVC is re-created by the statefulset controller, Karpenter still doesn't see that this pod is schedulable and waits around for ~5m before it begins launching a pod for the node.

There is no log on Karpenter's side that indicates why it is ignoring the pod or why it is not launching a node.

```bash
{"level":"DEBUG","time":"2024-02-19T20:11:02.842Z","logger":"controller.disruption","message":"ignoring pod, getting persistent volume claim \"www-web-2\", PersistentVolumeClaim \"www-web-2\" not found","commit":"3a8dd3a","pod":"default/web-2"}
{"level":"DEBUG","time":"2024-02-19T20:11:02.864Z","logger":"controller.disruption","message":"ignoring pod, getting persistent volume claim \"www-web-2\", PersistentVolumeClaim \"www-web-2\" not found","commit":"3a8dd3a","pod":"default/web-2"}
{"level":"DEBUG","time":"2024-02-19T20:11:04.752Z","logger":"controller.provisioner","message":"ignoring pod, getting persistent volume claim \"www-web-2\", PersistentVolumeClaim \"www-web-2\" not found","commit":"3a8dd3a","pod":"default/web-2"}
{"level":"DEBUG","time":"2024-02-19T20:11:14.752Z","logger":"controller.provisioner","message":"ignoring pod, getting persistent volume claim \"www-web-2\", PersistentVolumeClaim \"www-web-2\" not found","commit":"3a8dd3a","pod":"default/web-2"}
{"level":"DEBUG","time":"2024-02-19T20:11:43.031Z","logger":"controller.disruption","message":"discovered subnets","commit":"3a8dd3a","subnets":["subnet-006396cb4eae056f1 (us-west-2b)","subnet-0c31672d8f3da27ee (us-west-2b)","subnet-0e8ac99bc70aa8051 (us-west-2d)","subnet-068b2a87ec024682c (us-west-2d)","subnet-0f03dba293533e055 (us-west-2a)","subnet-0ff6eb107cd458d60 (us-west-2a)"]}
{"level":"DEBUG","time":"2024-02-19T20:11:49.218Z","logger":"controller","message":"deleted launch template","commit":"3a8dd3a","id":"lt-0747043e0ede53f50","name":"karpenter.k8s.aws/2974937103651069208"}
{"level":"ERROR","time":"2024-02-19T20:12:54.413Z","logger":"controller.nodeclaim.consistency","message":"check failed, expected 234 of resource pods, but found 110 (47.0% of expected)","commit":"3a8dd3a","nodeclaim":"default-wcpwn"}
{"level":"INFO","time":"2024-02-19T20:16:24.258Z","logger":"controller.provisioner","message":"found provisionable pod(s)","commit":"3a8dd3a","pods":"default/web-2","duration":"5.775834ms"}
```

**Expected Behavior**:

Karpenter should react to schedule the pod as soon as the pod shows that it can be schedulable.

**Reproduction Steps** (Please include YAML):

[nvme-testing.tar.gz](https://github.com/kubernetes-sigs/karpenter/files/14336824/nvme-testing.tar.gz)

**Versions**: 
- Chart Version: v0.34.0
- Kubernetes Version (`kubectl version`): 1.29

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
Here's an example of the `kube-scheduler` sitting here hanging in a pending state when there are nodes available and Karpenter thinks that the pod should schedule (and it should).

```bash
➜  karpenter-provider-aws git:(main) k get pods -A
NAMESPACE     NAME                                                     READY   STATUS    RESTARTS   AGE
default       local-volume-node-cleanup-controller-78767bc5c4-bmvwd    1/1     Running   0          5h7m
default       release-name-local-static-provisioner-7qxq2              1/1     Running   0          2m13s
default       release-name-local-static-provisioner-m2h5r              1/1     Running   0          2m56s
default       web-0                                                    0/1     Pending   0          100s
default       web-1                                                    1/1     Running   0          2m50s
```

```bash
➜  karpenter-provider-aws git:(main) k describe pod -n default       web-0
Name:             web-0
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           app=nginx
                  apps.kubernetes.io/pod-index=0
                  controller-revision-hash=web-5f69958999
                  statefulset.kubernetes.io/pod-name=web-0
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    StatefulSet/web
Containers:
  nginx:
    Image:        registry.k8s.io/nginx-slim:0.8
    Port:         80/TCP
    Host Port:    0/TCP
    Environment:  <none>
    Mounts:
      /usr/share/nginx/html from www (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xt9rk (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  www:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  www-web-0
    ReadOnly:   false
  kube-api-access-xt9rk:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  107s  default-scheduler  0/16 nodes are available: 1 node(s) had untolerated taint {karpenter.sh/disruption: disrupting}. preemption: 0/16 nodes are available: 1 Preemption is not helpful for scheduling, 15 No preemption victims found for incoming pod..
  Normal   Nominated         106s  karpenter          Pod should schedule on: nodeclaim/default-897jf, node/ip-192-168-103-34.us-west-2.compute.internal
```

```bash
➜  karpenter-provider-aws git:(main) k get pvc -A
NAMESPACE    NAME                                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default      www-web-0                           Pending                                                                        k8s-disks      117s
default      www-web-1                           Bound     local-pv-ef11af16                          279Gi      RWO            k8s-disks      3m9s
```

```bash
➜  karpenter-provider-aws git:(main) k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                                          STORAGECLASS   REASON   AGE
local-pv-6623f7d1                          279Gi      RWO            Delete           Available                                                    k8s-disks               3m57s
local-pv-71cc7caa                          279Gi      RWO            Delete           Available                                                    k8s-disks               3m57s
local-pv-97fa2c11                          279Gi      RWO            Delete           Available                                                    k8s-disks               4m40s
local-pv-ef11af16                          279Gi      RWO            Delete           Bound         default/www-web-1                              k8s-disks               4m40s
```

**Comment by jonathan-innis** [comment]
Looking deeper at the `kube-scheduler` logs, I see `"Updated PersistentVolume with claim. Waiting for binding to complete" pod="default/web-2" PV="local-pv-4e9780eb" PVC="default/www-web-2"` after 5m. Not sure if there is something going on with the new PVC that is preventing the pod from finishing its bind and scheduling.

**Comment by pkit** [comment]
Why the f it is closed??
Karpenter is not usable for stateful sets at all.
```
Warning  FailedAttachVolume  4m37s  attachdetach-controller  Multi-Attach error for volume "pvc-bafe9e7c-7039-4868-b4f0-54f61ac63548" Volume is already exclusively attached to one node and can't be attached to another
```
It's a full stop issue!

**Comment by jonathan-innis** [comment]
> Karpenter is not usable for stateful sets at all.

@pkit Can you describe the specific case that you are running into? Like the step-by-step of what is happening? Karpenter is trying to roll the nodes with stateful sets and it's not able to reschedule the pods?

**Comment by pkit** [comment]
@jonathan-innis yes. It tries to roll out a new SS (for example image upgrade)
Because it needs to start up a new node and shutdown the old node (nodes are sized to fit one pod) it does so in a way that new nodes are stuck in "Multi-Attach error" for 5-6 min.
And that happens almost every time on a loaded system (I suspect some timeout issues).

It's kinda ok if nodes in your SS are "replicated", but if the nodes are shards it leads to essentially 5 min of unavailability.
I'm ok with seconds of unavailability (otherwise I would write support for replication into our services) but creating support for replication just because of this problem looks like a bad idea.
I've rolled out a new eks with 1.31 and karpenter 1.0.8 (people said it doesn't do it anymore) but it will take some time to test the scenarios.

**Comment by prad9192** [comment]
Noticing this issue, when we already have few uneven nodes bootstrapped  in three zones, apply the below stateful set to replicate the issue.

**Nodepool for your Nodeclass**
```
cat <<EOF | k apply -f -
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-007
spec:
  disruption:
    budgets:
      - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 10k
    memory: 10000Gi
  template:
    metadata:
      labels:
        affinity: general-007
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: <REPLACE YOUR NODECLASS>
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-cpu
          operator: Gt
          values:
            - "1"
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - r5
      startupTaints:
        - effect: NoExecute
          key: ebs.csi.aws.com/agent-not-ready
      taints:
        - effect: NoSchedule
          key: workerrole
          value: general-007
---

---
EOF
```


**Workload**
```
cat <<EOF | k apply -f -
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-aaa
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-bbb
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---   
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ccc
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ddd
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-eee
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-fff
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-ggg
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---   
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-hhh
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-jjj
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-iii
  namespace: default
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: 3
  selector:
      matchLabels:
        app: test
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  template:
    metadata:
        labels:
          app: test
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          volumeMounts:
          - mountPath: /tmp
            name: tmp
          - mountPath: /data
            name: test-data
      volumes:
        - emptyDir:
            sizeLimit: 1Gi
          name: tmp
      imagePullSecrets:
      - name: registry-credentials
      nodeSelector:
        affinity: general-007
      tolerations:
      - effect: NoSchedule
        key: workerrole
        value: general-007
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: test
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: test-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
      volumeMode: Filesystem
---
EOF
```
