### ISSUE TITLE
NodePool disruption budget doesn't work

### ISSUE THREAD

**Issue by adovy** [kubernetes-sigs/karpenter#1066]
### Description

**Observed Behavior**:
Deployed NodePool disruption budget to not do deprovisioning on weekdays, but nodes are still being deprovisioned.
Also I don't see budget field when describing my deployed NodePool config

**Expected Behavior**:
working NodePool disruption budget 

**Reproduction Steps** (Please include YAML):

```
disruption:
  consolidationPolicy: WhenUnderutilized
  expireAfter: 720h
  budgets: 
  - schedule: "0 * * * mon-fri"
    duration: 1h
    nodes: 0
  - nodes: 10%
 ```

**Versions**:
- Chart Version: 0.35.0
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Are you in UTC time? The schedule should only be considering the nodes in UTC time. 

Please post your logs so we can see when these disruptions are occurring

**Comment by njtran** [comment]
I just tried your budgets spec on my cluster, and it's blocking all disruption. 

This may just be the way your kubectl output was returned, but I believe your existing configuration should have failed since there'd need to be quotes around the `nodes: 0` for the it to be recognized as a string and not an int.  
```
  budgets: 
  - schedule: "0 * * * mon-fri"
    duration: 1h
    nodes: "0"
  - nodes: 10%
```

Can you try this and see if this changes anything?

**Comment by adovy** [comment]
actually the problem is that helm release didn't update nodepool crds

**Comment by ccortinhas-pmi** [comment]
I have exactly the same issue with Karpenter v0.34.1.
Additionally, I tried to edit the NodePool resource directly via 'kubectl edit', and add the lines @njtran suggested:
```
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 10m0s
    budgets:
    - schedule: "0 * * * mon-fri"
      duration: 1h
      nodes: "0"
    - nodes: 10%
 ```
 and it errors with:
`strict decoding error: unknown field "spec.disruption.budgets"`
