### ISSUE TITLE
Not all nodeAffinity requirements are not taken into NodeClaim

### ISSUE THREAD

**Issue by cagataygurturk** [kubernetes-sigs/karpenter#1087]
### Description

**Observed Behavior**:

We are developing a custom provider and we believe we encountered a bug. 

We have two custom labels which we register as well-known labels. The labels are `example.com/instance-accelerator-manufacturer` and `example.com/platform`.

We have only one NodePool and the idea is that once Karpenter creates the NodeClaim, our provider reads these two labels to decide which type of node and where to provision. 

NodePool is pretty simple:

```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: example
spec:
  template:
    spec:
      requirements: []
      nodeClassRef:
        name: nil
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
```

Now, when we add the labels to the nodeSelector, the NodeClaim is populated by the label values correctly

So, for

```
    spec:
      nodeSelector:
        example.com/instance-accelerator-manufacturer: nvidia
        example.com/platform: aws
```

we get the following NodeClaim:

```
apiVersion: karpenter.sh/v1beta1
kind: NodeClaim
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "18334584923024176540"
  creationTimestamp: "2024-03-11T13:26:51Z"
  finalizers:
  - karpenter.sh/termination
  generateName: example-
  generation: 1
  labels:
    karpenter.sh/nodepool: example
  name: example-q2pqf
...
spec:
  nodeClassRef:
    name: nil
  requirements:
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - example
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - e2-medium
    - e2-standard-2
  - key: example.com/instance-accelerator-manufacturer
    operator: In
    values:
    - nvidia
  - key: example.com/platform
    operator: In
    values:
    - aws
```

When the nodeSelector terms are moved to nodeAffinity rules like this:

```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: example.com/instance-accelerator-manufacturer
                    operator: In
                    values:
                      - nvidia
              - matchExpressions:
                  - key: example.com/platform
                    operator: In
                    values:
                      - aws
```

Then the resulting NodePool only contains the very first nodeSelectorTerm, and the rest is completely dropped:

```
  requirements:
  - key: karpenter.sh/nodepool
    operator: In
    values:
    - example
  - key: node.kubernetes.io/instance-type
    operator: In
    values:
    - e2-medium
    - e2-standard-2
  - key: example.com/instance-accelerator-manufacturer
    operator: In
    values:
    - nvidia
```

It seems the offending piece of code is the following:

Here the nodeSelector terms are completely taken into NodePool specification:
https://github.com/kubernetes-sigs/karpenter/blob/1b873b5037263dbd953c6c86cb57355a49fa4704/pkg/scheduling/requirements.go#L91 

However, for some reason only the first nodeSelector term is taken into NodePool specification:

https://github.com/kubernetes-sigs/karpenter/blob/1b873b5037263dbd953c6c86cb57355a49fa4704/pkg/scheduling/requirements.go#L104

**Expected Behavior**:

NodeSelector and nodeAffinity rules must be treated equally.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jonathan-innis** [comment]
@cagataygurturk When you are using `nodeSelectorTerms`, are you intending to have those terms ANDed together or ORed? Karpenter is technically respecting one of the terms, which does meet the criteria for [`nodeSelectorTerms` defined in the docs](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity:~:text=If%20you%20specify%20multiple%20terms%20in%20nodeSelectorTerms%20associated%20with%20nodeAffinity%20types%2C%20then%20the%20Pod%20can%20be%20scheduled%20onto%20a%20node%20if%20one%20of%20the%20specified%20terms%20can%20be%20satisfied%20(terms%20are%20ORed).

I'm wondering if you meant to do
```
spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                  - key: example.com/instance-accelerator-manufacturer
                    operator: In
                    values:
                      - nvidia
                  - key: example.com/platform
                    operator: In
                    values:
                      - aws                  
```
