### ISSUE TITLE
Karpenter Not Scaling Properly for Specific Instance Type (c4.4xlarge)

### ISSUE THREAD

**Issue by byambadorjp** [kubernetes-sigs/karpenter#1088]
### Description

**Observed Behavior**:
Our pod, which typically runs every one hour with a duration of 30 minutes, has been experiencing issues for the past three days. It previously ran without any problems for a month. The issue is detailed below:

Karpenter is incompatible with nodepool "c4.4xlarge". The daemonset overhead is specified as {"cpu":"200m","memory":"50Mi","pods":"4"}. However, no instance type satisfies the resources {"cpu":"200m","memory":"25650Mi","pods":"5"} and requirements mentioned in [c4.4xlarge].

c4.4xlarge nodepool
```yml
Spec:
  Disruption:
    Consolidate After:     60s
    Consolidation Policy:  WhenEmpty
    Expire After:          720h
  Template:
    Metadata:
      Labels:
        Ana:  c4.4xlarge
    Spec:
      Node Class Ref:
        Name:  ana-cpu
      Requirements:
        Key:       node.kubernetes.io/instance-type
        Operator:  In
        Values:
          c4.4xlarge
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          spot
          on-demand
        Key:       kubernetes.io/arch
        Operator:  In
        Values:
          amd64
      Taints:
        Effect:  NoSchedule
        Key:     ana
        Value:   c4.4xlarge
```

**Expected Behavior**:
Pods should schedule properly on the specified instance type.

**Reproduction Steps** (Please include YAML):
We have a pod that runs every one hour with a duration of 30 minutes. Its resource settings are:
```yml
    Limits:
      memory:  25Gi
    Requests:
      memory:  25Gi
```

**Versions**:
- Chart Version: v0.33.0

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
