### ISSUE TITLE
Non-working consolidation starting from v0.32 with multiple NodePools with metadata labels

### ISSUE THREAD

**Issue by nantiferov** [kubernetes-sigs/karpenter#1106]
### Description

**Observed Behavior**:

Apparently something happened from v0.32, which causes both old Provisioners and new NodePools not able to consolidate initially launched instances with smaller/cheaper ones. I tried update to latest v0.35.2 with same results.

Quick search around issues in this repo and https://github.com/aws/karpenter-provider-aws didn't help to find anything similar.

My use case is that I need EBS volume be relative to total memory on EC2 instance. Since it's [impossible](https://github.com/aws/karpenter-provider-aws/issues/2394), I create couple of EC2NodeClass/NodePool with different volumeSize in blockDeviceMappings.

**Expected Behavior**:

Before v0.32, karpenter was consolidating launched nodes with smaller ones according to nodes utilisation. Right now it seems that both old Provisioners and new NodePools are not consolidated.

In karpenter logs I have this `{"level":"ERROR","time":"2024-03-15T16:35:54.861Z","logger":"controller.nodeclaim.consistency","message":"check failed, expected 20Gi of resource ephemeral-storage, but found 12561388Ki (59.9% of expected)","commit":"8b2d1d7","nodeclaim":"eng-8gb-7v6zh"}` and in node describe this:

```log
Events:
  Type    Reason            Age                    From       Message
  ----    ------            ----                   ----       -------
  Normal  Unconsolidatable  42m (x223 over 3d11h)  karpenter  Can't replace with a cheaper node
```

**Reproduction Steps** (Please include YAML):

Yaml are based on current setup and slightly simplified (removed tags, keep only 2 )

EC2NodeClass
```yaml
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: eng-12gb # EBS volume size
spec:
  amiFamily: AL2
  role: Karpenter-clustername

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 12Gi # add 4Gb to instance memory for host OS
        volumeType: gp3

  securityGroupSelectorTerms:
    - tags:
        Name: clustername-node

  subnetSelectorTerms:
    - tags:
        Name: SomeSG-a
    - tags:
        Name: SomeSG-b
    - tags:
        Name: SomeSG-c
```

```yaml
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: eng-20gb # EBS volume size
spec:
  amiFamily: AL2
  role: Karpenter-clustername

  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 20Gi # add 4Gb to instance memory for host OS
        volumeType: gp3

  securityGroupSelectorTerms:
    - tags:
        Name: clustername-node

  subnetSelectorTerms:
    - tags:
        Name: SomeSG-a
    - tags:
        Name: SomeSG-b
    - tags:
        Name: SomeSG-c
```

NodePool
```yaml
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: eng-8gb # EC2 total memory
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never

  limits:
    cpu: "50"
    memory: 100Gi

  template:
    spec:
      metadata:
        labels:
          some: label
      nodeClassRef:
        name: eng-12gb # metadata.name from EC2NodeClass
      kubelet:
        systemReserved:
          memory: 300Mi
      taints:
        - key: something
          value: special
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - t4g
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - "8192"
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - eu-central-1a
            - eu-central-1b
            - eu-central-1c
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
```

```yaml
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: eng-16gb # EC2 total memory
spec:
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never

  limits:
    cpu: "50"
    memory: 100Gi

  template:
    spec:
      metadata:
        labels:
          some: label
      nodeClassRef:
        name: eng-20gb # metadata.name from EC2NodeClass
      kubelet:
        systemReserved:
          memory: 1Gi
      taints:
        - key: something
          value: special
          effect: NoSchedule
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - t4g
        - key: karpenter.k8s.aws/instance-memory
          operator: In
          values:
            - "16384"
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - eu-central-1a
            - eu-central-1b
            - eu-central-1c
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
```

And then some deployment or couple of them to schedule on these nodes:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: some
                    operator: In
                    values:
                      - label
      tolerations:
        - key: something
          value: special
          effect: NoSchedule
      containers:
        - name: nginx
          image: nginx:stable
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 1Gi
```

So before 0.32 karpenter was launching slightly bigger nodes in the beginning and then after ~30 min was optimising them. Right now it's launching suboptimal nodes and keeps them with aforementioned errors in logs and messages in events.

**Versions**:
- Chart Version: karpenter-v0.32.7
- Kubernetes Version (`kubectl version`): v1.28.5-eks-5e0fdde

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
