### ISSUE TITLE
New nodes are not getting created, when existing node draining gets blocked due to pdb.

### ISSUE THREAD

**Issue by bhaskar-reddy** [kubernetes-sigs/karpenter#1121]
### Description

**Observed Behavior**:
Karpenter did not bring up new nodes at all with 80+ pods in pending state. 
This happened last night in a lower env when there was an argocd update made, and couple of nodes were not able to be drained due to pdb. Their respective nodeclaims were still showing up with a Node IP while the node itself seems to have been removed (when checked via eks-node-viewer). Here are the karpenter logs which helped me identify the PDB issue:
> kube-system/karpenter-6465666966-4q49j[controller]: {"level":"INFO","time":"2024-03-19T02:48:43.298Z","logger":"controller","message":"Starting workers","commit":"2c8f2a5","controller":"state.daemonset","controllerGroup":"apps","controllerKind":"DaemonSet","worker count":10}
> kube-system/karpenter-6465666966-4q49j[controller]: {"level":"ERROR","time":"2024-03-19T02:48:43.312Z","logger":"controller.nodeclaim.consistency","message":"**check failed, can't drain node, PDB \"istio-system/istiod\" is blocking evictions**","commit":"2c8f2a5","nodeclaim":"eks-unmanaged-amd64-dcg87"}
> kube-system/karpenter-6465666966-4q49j[controller]: {"level":"ERROR","time":"2024-03-19T02:48:43.321Z","logger":"controller.nodeclaim.consistency","message":"**check failed, can't drain node, PDB \"istio-gateway/istio-ingressgateway\" is blocking evictions**","commit":"2c8f2a5","nodeclaim":"eks-unmanaged-amd64-5fxqt"}
> kube-system/karpenter-6465666966-4q49j[controller]: {"level":"ERROR","time":"2024-03-19T02:48:44.192Z","logger":"controller.disruption","message":"listing instance types for eks-unmanaged-amd64, resolving node class, ec2nodeclasses.karpenter.sh \"eks-unmanaged-amd64\" is terminating, treating as not found","commit":"2c8f2a5"}

What was surprising was that all the nodes that were managed by karpenter were down, and there was no new node that came up until I managed to manually delete the pods with pdb; which then removed the 2 existing nodeclaims, and the controller then initiated new nodeclaims/nodes with pods being scheduled by scheduler as expected. Note that Karpenter controller along with NodePool/EC2NodeClass (separate Argo Applications) is defined in argocd, as are other system applications.

**Expected Behavior**:
Irrespective of the pods having PDB that is blocking evictions, that thereby can't drain node/s; new nodes need to be provisioned by Karpenter when there are pending pods.

**Reproduction Steps** (Please include YAML):
_NodePool spec:_
```
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: Never
  template:
    spec:
      kubelet:
        clusterDNS:
        - 1xx.2yy.xx.yy
        evictionHard:
          memory.available: 200Mi
          nodefs.available: 10%
        kubeReserved:
          cpu: 300m
          ephemeral-storage: 1Gi
          memory: 300Mi
        maxPods: 100
        systemReserved:
          cpu: 300m
          ephemeral-storage: 1Gi
          memory: 300Mi
      nodeClassRef:
        name: eks-unmanaged-amd64
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - c6i.4xlarge
      - key: topology.kubernetes.io/zone
        operator: In
        values:
        - us-west-2a
        - us-west-2b
        - us-west-2c
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
```

**Versions**:
- Chart Version: `karpenter v0.35`
- Kubernetes Version (`kubectl version`):
```
❯ k version
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.1-eks-508b6b3
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
