### ISSUE TITLE
karpenter evicts DaemonSet pods before all service pods are terminated

### ISSUE THREAD

**Issue by robertoriv** [kubernetes-sigs/karpenter#1133]
### Description

**Observed Behavior**:

When draining a node, karpenter will evict all service pods (managed by Deployments) and then evict the DaemonSet pods running on the node. However, it starts evicting DaemonSet pods before the service pods are entirely gone. 

We use a `preStopHook` to flush metrics and/or drain the pods out of the ALBs. The observed behavior will cause a pod to run in `Terminating` status for a while, without the DaemonSets required to support it -- in our case: metrics, logging. This results in loss of metrics and logs.

Example:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service
  namespace: my-service
  labels:
    app: my-service
spec:
  template:
    metadata:
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: ...
        command: ...
        env: ...

        lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","curl -X GET \"$POD_IP:3000/flush?delay=120\" > /proc/1/fd/1"]
      terminationGracePeriodSeconds: 135
```

The events look like this:
```
❯ k get events -A | grep -E "my-service-d977cd6fd-w494k|datadog-agent-jv5nz|vector-logging-246l7"
my-service                34s         Normal    Evicted                     pod/my-service-d977cd6fd-w494k                                  Evicted pod
my-service                34s         Normal    Killing                     pod/my-service-d977cd6fd-w494k                                  Stopping container my-service
monitoring                33s         Normal    Evicted                     pod/datadog-agent-jv5nz                                           Evicted pod
monitoring                33s         Normal    Killing                     pod/datadog-agent-jv5nz                                           Stopping container agent
monitoring                33s         Normal    Evicted                     pod/vector-logging-246l7                                          Evicted pod
monitoring                33s         Normal    Killing                     pod/vector-logging-246l7                                          Stopping container vector
```
(There's a 1s gap between the "request" to evict `my-service`, and the request to evict `datadog-agent` and `vector-logging`. `my-service` will delay termination by `120s`, and we would expect datadog and vector to hand around until then.)

The `my-service` pod is still `Terminating` 97s after the replacement pod was scheduled:
```
❯ k get pods -n my-service
NAME                           READY   STATUS        RESTARTS   AGE
my-service-d977cd6fd-t8vn8   1/1     Running       0          97s          # replacement pod
my-service-d977cd6fd-w494k   1/1     Terminating   0          94m          # old pod still Terminating
my-service-d977cd6fd-zkt5k   1/1     Running       0          4m5s
```

It looks like karpenter begins evicting the DaemonSets as soon as it gets an "ack" for the eviction request for the last non-DaemonSet pod. We see logs for around 15s after the eviction begins for the last service pod, and then the vector pod gets shut down.

Note: Some DaemonSet pods remain available after the DaemonSet evictions begin -- for example: `cilium`, `node-problem-detector`. Those DaemonSets have very permissive tolerations, which aligns with: https://github.com/kubernetes-sigs/karpenter/issues/621#issuecomment-1773345054. We would prefer not to have to add such permissive tolerations to _every_ DaemonSet we run, because deploying some DaemonSets on a node that has been tainted with "NoSchedule" for a legitimate reason could be problematic.

**Expected Behavior**:

karpenter should wait until the last non-DaemonSet pod is completely gone before it starts evicting DaemonSet pods.

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: v0.32.5
- Kubernetes Version (`kubectl version`): v1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
