### ISSUE TITLE
Question: how Karpenter play with the default PodTopologySpread part of KubeSchedulerConfiguration?

### ISSUE THREAD

**Issue by myaser** [kubernetes-sigs/karpenter#1197]
I was wondering what karpenter would do by default in terms of spreading pods across nodes and availability zones?

- is there any default built in karpenter in case a pod did not define topologySpreadConstraints?
- does it honor the [built in constraints](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints) of the scheduler?
- in case the [default was customized](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#cluster-level-default-constraints), would karpenter know and honor the new default?

related:
[CA related issue](https://github.com/kubernetes/autoscaler/issues/3879)

**Comment by myaser** [comment]
please remove the stale state

**Comment by wenn** [comment]
Bump. 

We have PodTopologySpread on individual Deployment resources, and Karpenter acts on it. The cluster [default is on](https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/#internal-default-constraints). 

```
defaultConstraints:
  - maxSkew: 3
    topologyKey: "kubernetes.io/hostname"
    whenUnsatisfiable: ScheduleAnyway
  - maxSkew: 5
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: ScheduleAnyway
```

We didn't see spreading behavior before explicitly setting it on deployments, so I guess - Karpenter does not respect cluster level pod spreading.
