### ISSUE TITLE
Karpenter Schedule for Node Disruption 

### ISSUE THREAD

**Issue by tarunmittal24** [kubernetes-sigs/karpenter#1264]
Hi I am facing a issue in which the node got refreshed, one's the new ami is being released by the aws team, as i have not mentioned the ami-selector terms this is a expected behaviour, but as per security i need to update image every 30 days, that i have handled with the **expireAfter: 720h** in the nodepool config, But the case is, if i mentioned the ami-selector terms and put the specific image-ami-id, even after it got expired in the 30 days it will take the same image.

Any way to control this, like want the new nodes will comes after x days, with the new ami as that particular point of time and want that it should happened during the specific schedule like on weekends [Saturday (2-3 am)], not on weekdays.

My Current Config

**Node-pool.yaml**
```
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: core
spec:
  disruption:
    consolidateAfter: Never
    expireAfter: 720h
    consolidationPolicy: WhenEmpty
    budgets:
      - nodes: 10%
      - schedule: "0 0 * * mon-fri"
        duration: 24h
        nodes: "0"
  limits:
    cpu: "12"
    memory: 45Gi
  template:
    metadata:
      labels:
        node: core
    spec:
      taints:
        - key: "node"
          value: "core"
          effect: "NoSchedule"
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1beta1
        kind: EC2NodeClass
        name: core
      kubelet: 
        maxPods: 110
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: 
          - m5a.large
          - m6a.large
          - m6i.large
          - m5.large
          - m4.large
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type	
        operator: In	
        values:
          - on-demand
 ```
 
 **node-class.yaml**
 
 ```
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: core
spec:
  amiFamily: AL2
  metadataOptions:
    httpEndpoint: enabled
    httpTokens: required
  subnetSelectorTerms:
    - tags:
        karpenter.sh/zfh-prod/team: "infra"
        aws-cdk:subnet-name: "EKSPrivate"
  securityGroupSelectorTerms:
    - id: "sg-009b2e138f9263f3d" 
  role: "PROD-EKS-KarpenterNode"  
  tags:
    Name: PROD-EKS/karpenter.sh/core
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
```
