### ISSUE TITLE
Pod cannot be scheduled with preferred affinity

### ISSUE THREAD

**Issue by marsn** [kubernetes-sigs/karpenter#1265]
### Description

**Observed Behavior**:
Karpenter ignores pods with preferred affinity rule
```
 affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
              - key: karpenter.sh/nodepool
                operator: DoesNotExist
```
**Expected Behavior**:
New node gets created

**Comment by jmdeal** [comment]
This seems reasonable to support, but could you expand upon your use case? Karpenter will only provision new new nodes when pods are unschedulable, i.e. no more room on existing capacity. The main benefit here would be to prefer non-Karpenter capacity when there is available room on nodes previously provisioned by Karpenter and other capacity. Does that sound about right, or did you have a different use case?

**Comment by dimitri-fert** [comment]
I recently opened a very similar issue that I closed in favor of this one.

To sum up (you'll find full details in the PR mentionned by @jigisha620), we unexpectedly lost a node after applying this soft affinity as the PV associated to our pod got ignored while having a zonal constraint on this node (zone A). 

Given this PV was the only constraint on zone A ; the 2 other nodes (zone B and zone C) had enough capacity to handle the workload of zone A ; it was cheaper to keep only 2 nodes  ; other nodes had zonal constraints and had to be maintained ;  the node of zone A got drained by Karpenter. The scheduler was then unable to schedule the pods due to volume node affinity conflict (blocked in Pending state).

No doubt it makes sense to follow this behaviour when using a hard affinity as there' s a guarantee the pod will never be schedueled on a node provisionned by Karpenter, but with a soft affinity we lose this guarantee and could get stuck.

**Comment by fmuyassarov** [comment]
@jonathan-innis Would it be okay if I take this task?

**Comment by zarko-a** [comment]
We've experienced the same issue with `requiredDuringSchedulingIgnoredDuringExecution` 

```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/spot-worker
            operator: DoesNotExist
```

Pods never get scheduled even though nodes don't have the `node-role.kubernetes.io/spot-worker` label. Karpenter doesn't even create a nodeClaim. Removing this affinity resolves the problem right away.
