### ISSUE TITLE
Inconsistent interpretation of "preferred" `affinity` between `kube-scheduler` and `karpenter`

### ISSUE THREAD

**Issue by duxing** [kubernetes-sigs/karpenter#1300]
### Description

**Observed Behavior**:
I'm testing cluster autoscaling activities using a deployment of a simple hello world HTTP server: `kubectl scale --replicas=X deploy/my-hello-world -n my-ns` and I noticed this behavior after setting a `preferredDuringSchedulingIgnoredDuringExecution` `podAntiAffinity` for my deployment template.  Related `karpenter` configuration are set to default values ([`.settings.batchMaxDuration`](https://github.com/aws/karpenter-provider-aws/blob/fdae78553f915c2317fd8a47d757f022800c2d03/charts/karpenter/values.yaml#L174) and [`.settings.batchIdleDuration`](https://github.com/aws/karpenter-provider-aws/blob/fdae78553f915c2317fd8a47d757f022800c2d03/charts/karpenter/values.yaml#L178))

allow me to use a concrete example to describe the issue: 
1. `my-hello-world` has `requiredDuringSchedulingIgnoredDuringExecution` `nodeAffinity` to pin to a particular `NodePool` `my-pool` (exists in `karpenter`). example `yaml` attached in reproduce steps. 
2. `my-pool` is configured to have capacity of 32 nodes (see attached specification in reproduce steps).
3.  assume the `my-pool` is also used by other workloads and we have 3 nodes already running with some available spaces.
4. when I scale the deployment to **100** `replica`s to trigger node scale up: 40 pods fit into existing nodes where 60 are pending due to insufficient resources.
5. due to the `preferred` `podAntiAffinity`, `karpenter` tries to scale up one node per pending pod rather than consolidating all of them into 1~2 nodes: 29 (32 capacity - 3 existing) nodeclaims were created and a few minutes later, all 29 new nodes finished initialization and become ready (however, become ready at different time)
6. I'm not 100% sure if `kube-scheduler` is aware of `nodeclaim`s but it definitely is aware of `node`s: ` kube-scheduler` puts all pending 60 pods on to the first 2 nodes that become available.
7. a few minutes later, `karpenter` terminates 27 out of 29 nodes because they're empty.

I noticed logs from `karpenter` has a related log:
> “pod my-ns/my-hello-world-5cb44f895-fvz5n has a preferred Anti-Affinity which can prevent consolidation

this results in a large number of redundant node launch + termination and it's later found out that this behavior burned the AWS ENI API resource quota, leading to a situation that new nodes can't be initialized due to VPC CNI hitting AWS API rate limit constantly

**Expected Behavior**:

The different context scope between `kube-scheduler` and `karpenter` and the responsibility boundary split is the root of this issue:
 - `kube-scheduler` interprets `affinity` but is limited to what nodes are available. even if `karpenter` tries to respect the `preferredDuringSchedulingIgnoredDuringExecution` `podAntiAffinity`, `kube-scheduler` works with what nodes are ready. This seems right to me and I think `kube-scheduler` should continue to be `nodeclaim`-agnostic
 - `karpenter` has access to `node`s, `nodeclaim`s and also have the ability to create new `nodeclaim`s. I think `karpenter` is trying to be smart about what `kube-scheduler` **would do** but because different nodes are **not** atomically and synchronously created, this effort is completely wasted.

One of the 2 things should happen, but the expected result should be the same:
1. `karpenter` interprets `preferredDuringSchedulingIgnoredDuringExecution` `podAntiAffinity` in the same way as `kube-scheduler`: it knows that the 1st ready node would take precedence over preferred `podAnitAffinity`, and `kube-scheduler` don't have any context on what's coming (not ready `nodeclaim`s and to-be-created `nodeclaim`s), and create minimum amount of node to meet the resource needs
2. `karpenter` ignores the `preferredDuringSchedulingIgnoredDuringExecution` `podAntiAffinity` and create minimum amount of node to meet the resource needs

**Reproduction Steps** (Please include YAML):

affinity:
```
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pool
                operator: In
                values:
                - my-pool
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - my-hello-world
              topologyKey: kubernetes.io/hostname
            weight: 100
```

`NodePool`:
```
spec:
  disruption:
    consolidateAfter: 60s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: "512"
    memory: 4096Gi
  template:
    metadata:
      labels:
        pool: my-pool
    spec:
      nodeClassRef:
        name: my-node-class
      requirements:
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - r5.4xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
```

**Versions**:
- Chart Version: `v0.33.1`
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.29.3
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
