### ISSUE TITLE
Karpenter behaviour with Disruption Budget

### ISSUE THREAD

**Issue by thangle-grabtaxi** [kubernetes-sigs/karpenter#1350]
### Description

**Observed Behavior**:
When we make changes to Karpenter node pool, specifically AMI change, with a disruption budget of 100%, we expect Karpenter to rotate all nodes at once due to **Drift**. However, it only rotate 1 to 4 nodes at a time.

Disruption Budget is set to 100%, which comes out to be around 35-40 nodes.
<img width="1534" alt="image" src="https://github.com/kubernetes-sigs/karpenter/assets/143369045/1a4269c6-5c1f-4a57-b6b4-3e33c28a86c1">

During allowed disruption period of 10 minutes minutes, Karpenter rotate the instances in sequence, 1 to 4 nodes per batch.
<img width="1438" alt="image" src="https://github.com/kubernetes-sigs/karpenter/assets/143369045/85fb4fad-97de-4cf1-a27e-ab0e294a60ca">

This cause an issue of frequent restart for our applications. We have set specifically 100% disruption budget within a short time frame (10 mins) with the expectation of all nodes will be restarted only once, meaning only one restart for our applications.

**Expected Behavior**:
Karpenter rotate all nodes at once.

**Reproduction Steps** (Please include YAML):
```yaml
    apiVersion: karpenter.sh/v1beta1
    kind: NodePool
    metadata:
      name: <NODE_POOL_NAME>
    spec:
      template:
        metadata:
          labels:
            node_group_name: <NODE_POOL_NAME>
        spec:
          nodeClassRef:
            name: <NODE_CLASS_NAME>
          requirements:
            - key: "karpenter.k8s.aws/instance-hypervisor"
              operator: In
              values: ["nitro"]
            - key: "karpenter.sh/capacity-type"
              operator: In
              values: ["on-demand"]
            - key: kubernetes.io/os
              operator: NotIn
              values: ["windows"]
            - key: kubernetes.io/arch
              operator: In
              values: ["arm64", "amd64"]
            - key: "karpenter.k8s.aws/instance-generation"
              operator: Gt
              values: ["3"]
      disruption:
        consolidationPolicy: WhenUnderutilized
        expireAfter: Never
        budgets:
          # Disruption Window: 10 minutes from 3pm to 3.10pm SGT (7am to 7.10am UTC)
          # Disruption Impact: 100%
          # Non Disruption Window: From 3.10pm to 3pm SGT (7.10am to 7am UTC)
          - nodes: "0"
            schedule: "10 7 * * *"
            duration: "23h50m"
          - nodes: "100%"
      limits:
        cpu: "10000"
        memory: 10000Gi
```

**Versions**:
- Chart Version: v0.35.5
- Kubernetes Version (`kubectl version`): 1.27

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
