### ISSUE TITLE
Better scheduling with low-priority pods

### ISSUE THREAD

**Issue by WxFang** [kubernetes-sigs/karpenter#1437]
### Description

**What problem are you trying to solve?**
We're trying to migrate gpu workloads to karpenter. We have also deployed a daemonset called cost-placeholder. The idea is to deploy low-priority pods for better cost attribution of idle cost. And the spec looks as below:
```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodepool
                operator: In
                values:
                - gpu-p5-48-llm
                       
       resources:
          limits:
            cpu: "191"
            memory: 1995G
            nvidia.com/gpu: "8"
          requests:
            cpu: "191"
            memory: 1995G
            nvidia.com/gpu: "8"
      priorityClassName: low-priority
      restartPolicy: Always
      schedulerName: default-scheduler
```
But Karpenter is unable to schedule pods onto those gpu nodes because it counts the low-priority pod into workload thus the requested resources is over capacity:
```
daemonset overhead={"cpu":"191250m","memory":"1995268435456","nvidia.com/gpu":"8","pods":"7"},
no instance type satisfied resources 
{"cpu":"271250m","memory":"1995268437456","nvidia.com/gpu":"16","pods":"8"} and 
requirements karpenter.sh/capacity-type In [on-demand], 
karpenter.sh/nodepool In [gpu-p5-48-llm], 
kubernetes.io/arch In [amd64], 
kubernetes.io/os In [linux], 
node.kubernetes.io/instance-type In [p5.48xlarge], 
nodepool In [gpu-p5-48-llm], 
nvidia.com/gpu In [true] (no instance type has enough resources)
```

Related issue: https://github.com/aws/karpenter-provider-aws/issues/6507

**How important is this feature to you?**
This is really important for our cost attribution. 
GPU machines are expansive and have low availability and we use ODCR to reserve them. That means sometimes the machines can be empty and it's hard to attribute the (idle) cost since no workloads are running. 
So, we launch low-priority pods for this purpose. Without this feature, low-priority placeholder pods will block any pods to schedule onto those machines. 

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
