### ISSUE TITLE
Disruption budgets not workings as expected/documented

### ISSUE THREAD

**Issue by komapa** [kubernetes-sigs/karpenter#1438]
### Description

**Observed Behavior**:

Hello, we have the the following disruption budget on a NodePool:

```yaml
budgets:
    - nodes: "1"
    - duration: 60m
      nodes: 1%
      schedule: '@hourly'
    - duration: 17h
      nodes: "0"
      schedule: 0 9 * * *
```

**Expected Behavior**:

We expect, for a NodePool with around 200 nodes, to disrupt at most 2 nodes per hour out side of the 17h where we define no disruptions (nodes: 0). What we see though is disruptions happening at the a much higher rate. see the attached graph of `karpenter.karpenter_interruption_actions_performed.count` metric.

<img width="1268" alt="Screenshot 2024-07-18 at 1 03 48 AM" src="https://github.com/user-attachments/assets/1ef46e13-e605-40a4-9b20-8608cb27ed6d">

**Reproduction Steps** (Please include YAML):

```yaml
budgets:
    - nodes: "1"
    - duration: 60m
      nodes: 1%
      schedule: '@hourly'
    - duration: 17h
      nodes: "0"
      schedule: 0 9 * * *
```

**Versions**:
- Chart Version: `0.35.2`
- Kubernetes Version (`kubectl version`): `1.28.x`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
