### ISSUE TITLE
Consolidation: Unconsolidatable / Can't remove without creating 2 candidates

### ISSUE THREAD

**Issue by igorbdl** [kubernetes-sigs/karpenter#1442]
### Description

**Observed Behavior**:
Clusters grow to peak capacity, but then don't scale back down. 

There is one single node (managed by karpenter) left in each cluster dealing with all of the capacity after peak traffic, but the node only has 20% of requested CPU and memory and karpenter is not replacing that node by a more appropriate instance size.

The only node events:
  Normal  Unconsolidatable  44m (x268 over 3d1h)  karpenter  Can't remove without creating 2 candidates
  Normal  Unconsolidatable  35m                   karpenter  Can't remove without creating 2 candidates
  Normal  Unconsolidatable  4m1s (x3 over 34m)    karpenter  Can't remove without creating 2 candidates

I've set the log level to `debug` but it shows nothing of relevance.

**Expected Behavior**:
karpenter to consolidate and replace with a smaller node

**Reproduction Steps** (Please include YAML):
SpotToSpotConsolidation feature gate set to true

nodepool.yaml
``` yaml
[...]
    disruption:
      budgets:
      - nodes: 10%
      consolidationPolicy: WhenUnderutilized
[...]
```

Scale up the cluster, wait for karpenter to consolidate pods on a very large node. Scale pods back down. Observe a single node getting all the pods and remaining with a lot of free capacity, while karpenter won't replace it by a smaller node.

**Versions**:
- Chart Version: v0.37.0
- Kubernetes Version (`kubectl version`): 1.28.9

--- 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by njtran** [comment]
Can you share nodepools? Are you expecting spot to spot consolidation to occur? Seems like you might have large nodes, and only smaller instance type options are available, which is making it tough for Karpenter to consolidate. This could occur when you have required spreading on your deployments too

**Comment by igorbdl** [comment]
Hey @njtran thanks for your response :+1: 

Yes, I was expecting the spot to spot consolidation to take place as there was only 20% to 30% of requested capacity from that instance after the traffic spike. The nodepool is super simple:

```
  spec:
    disruption:
      budgets:
      - nodes: 10%
      consolidationPolicy: WhenUnderutilized
    template:
      metadata:
        labels:
          workloads: example
      spec:
        nodeClassRef:
          name: default
        requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
          - amd64
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
          - nitro
        - key: karpenter.sh/capacity-type
          operator: In
          values:
          - spot
          - on-demand
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
          - c
          - m
          - r
```

I've seen this across a number of regions - not in just a single one. I then deleted the nodeclaims and the instance was replaced by several smaller ones. As there was a single node at the time, could it be due to the disruption budget of 10%?

I've worked around this by setting a relatively short `expireAfter` so I haven't seen it happening again.

**Comment by njtran** [comment]
Can you share what the size of the instance was that Karpenter was attempting to consolidate? I find it hard to believe that it wouldn't try to consolidate, considering that you have a pretty wide open NodePool.

**Comment by igorbdl** [comment]
In a couple of regions it had a single `c5d.18xlarge` instance with:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                14335m (19%)   15750m (21%)
  memory             35424Mi (26%)  43634Mi (32%)
```

**Comment by nohant** [comment]
@igorbdl have you resolved?
mine is creating a `m6g.12xlarge` without any reason and will not scale back.
```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests       Limits
  --------           --------       ------
  cpu                2140m (4%)     25m (0%)
  memory             21849Mi (11%)  23743Mi (12%)
  ephemeral-storage  0 (0%)         0 (0%)
  hugepages-1Gi      0 (0%)         0 (0%)
  hugepages-2Mi      0 (0%)         0 (0%)
  hugepages-32Mi     0 (0%)         0 (0%)
  hugepages-64Ki     0 (0%)         0 (0%)
  ```

**Comment by igorbdl** [comment]
Hey @nohant I have setup a very short `expireAfter` (under 10 hours) to ensure if it happens that it gets cleared with it. After the nodeclaim is deleted, the karpenter right sizes the nodes. This is a workaround and I don't think the issue is resolved as it hasn't been addressed.

**Comment by nohant** [comment]
sadly i noticed its the standard way of working for karpenter.
im always with the biggest node possible from AWS.
```
    spec:
      expireAfter: 1h
      taints:
        - key: dedicated
          value: "runner"
          effect: NoSchedule
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: main
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["m"]
        - key: karpenter.k8s.aws/instance-local-nvme
          operator: DoesNotExist
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
  limits:
    memory: 32Gi
```
in order to dont go broke, i `have` to use limits.
@igorbdl your solution sadly will not work for me :(

**Comment by tm-nadavsh** [comment]
@nohant FYI

> sadly i noticed its the standard way of working for karpenter. im always with the biggest node possible from AWS.
> 
> ```
>     spec:
>       expireAfter: 1h
>       taints:
>         - key: dedicated
>           value: "runner"
>           effect: NoSchedule
>       nodeClassRef:
>         group: karpenter.k8s.aws
>         kind: EC2NodeClass
>         name: main
>       requirements:
>         - key: kubernetes.io/arch
>           operator: In
>           values: ["arm64"]
>         - key: karpenter.sh/capacity-type
>           operator: In
>           values: ["spot"]
>         - key: kubernetes.io/os
>           operator: In
>           values: ["linux"]
>         - key: karpenter.k8s.aws/instance-category
>           operator: In
>           values: ["m"]
>         - key: karpenter.k8s.aws/instance-local-nvme
>           operator: DoesNotExist
>   disruption:
>     consolidationPolicy: WhenEmptyOrUnderutilized
>     consolidateAfter: 1m
>   limits:
>     memory: 32Gi
> ```
> 
> in order to dont go broke, i `have` to use limits. @igorbdl your solution sadly will not work for me :(

putting consolidateAfter with `consolidationPolicy: WhenEmptyOrUnderutilized` does not work, from [documentation](https://karpenter.sh/v0.37/concepts/nodepools/):

> 
>     # The amount of time Karpenter should wait after discovering a consolidation decision
>     # This value can currently only be set when the consolidationPolicy is 'WhenEmpty'
>     # You can choose to disable consolidation entirely by setting the string value 'Never' here
>     consolidateAfter: 30s

But putting expireAfter with a relatively short time does look like a decent workaround.
I also added:
```
    budgets:
    - duration: 45m
      nodes: "0"
      schedule: '@hourly'
    - nodes: "2"
```
To fight a different issue that karpenter will create new nodes and remove them after after a really short time, doing so every few minutes is also not very efficient this limits karpenter to removing only 2 nodes each hour and only in the last 15 minutes on an hour.
 Again, not the most efficient way but also a workaround.

**Comment by igorbdl** [comment]
@tm-nadavsh do you have spot to spot consolidation feature gate enabled? only with it explicitly enabled (which is not by default), karpenter will consolidate spot nodes.

See [here](https://karpenter.sh/docs/concepts/disruption/#spot-consolidation)

My issue was that even with this enabled I had that problem some times

**Comment by nohant** [comment]
but i cant refuse consolidate after @tm-nadavsh 
`NodePool.karpenter.sh "worker" is invalid: [spec.disruption.consolidateAfter: Required value, <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation]`.

**Comment by tm-nadavsh** [comment]
@nohant what version of karpenter are you running, if its the latest(0.37.0) it seems like you have multiple misconfigurations,
`expireAfter: 1h` should be inside spec.disruption
WhenEmptyOrUnderutilized, not a real value, running `kubectl explain nodepools.karpenter.sh.spec.disruption`:

>   consolidationPolicy	<string>
>   enum: WhenEmpty, WhenUnderutilized
>     ConsolidationPolicy describes which nodes Karpenter can disrupt through its
>     consolidation
>     algorithm. This policy defaults to "WhenUnderutilized" if not specified

missing the template indentation after spec and more
maybe im missing something.

**Comment by tm-nadavsh** [comment]
@igorbdl As far as i understand, it does not matter if spot to spot consolidation is enabled regarding this issue, the issue is that karpenter does not scale down nodes when they are underutilized, i would think that if a node is underutilized, spot or on-demand, karpenter will scale it down because of `consolidationPolicy: WhenUnderutilized`.
But it looks like thats not always the case as you stated and i see in my cluster, multiple nodes with very low utilization and they are not scaled down, getting karpenter Can't remove without creating 2 candidates.
I still think that adding an `expireAfter: ` with relatively short time is somewhat of a workaround for that issue.

**Comment by nohant** [comment]
> @nohant what version of karpenter are you running, if its the latest(0.37.0) it seems like you have multiple misconfigurations, `expireAfter: 1h` should be inside spec.disruption WhenEmptyOrUnderutilized, not a real value, running `kubectl explain nodepools.karpenter.sh.spec.disruption`:
> 
> > consolidationPolicy	
> > enum: WhenEmpty, WhenUnderutilized
> > ConsolidationPolicy describes which nodes Karpenter can disrupt through its
> > consolidation
> > algorithm. This policy defaults to "WhenUnderutilized" if not specified
> 
> missing the template indentation after spec and more maybe im missing something.

Latest version is 1: https://karpenter.sh/v1.0/.
Im using this one, and in this configuration your suggestion dont work sadly xD

**Comment by irizzant** [comment]
I'm on version 0.37 too and I'm experiencing 
```
Events:
  Type    Reason            Age                 From       Message
  ----    ------            ----                ----       -------
  Normal  Unconsolidatable  11m (x9 over 165m)  karpenter  Can't remove without creating 2 candidates
```
This is an on-demand EC2 instance.

**Comment by jortkoopmans** [comment]
I think I'm seeing this as well. It is not strictly related to SpotToSpotConsolidation I believe (but I do have it enabled), as I would expect it would follow the regular (new) `WhenEmptyOrUnderutilized`.

When I end up with large nodes (here a r5a.12xlarge), I get the Event:
```
 Type    Reason            Age                  From       Message
 ----    ------            ----                 ----       -------  
 Normal  Unconsolidatable  6m10s (x5 over 67m)  karpenter  Can't remove without creating 2 candidates    
```

Versions:
k8s: 1.24 (I know this is not officially supported)
karpenter: 1.0.6

Nodepool (somewhat cleaned up):
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    compatibility.karpenter.sh/v1beta1-kubelet-conversion: '{"maxPods":110,"podsPerCore":20}'
    compatibility.karpenter.sh/v1beta1-nodeclass-reference: '{"name":"default"}'
    karpenter.sh/nodepool-hash: "10347628794191304157"
    karpenter.sh/nodepool-hash-version: v3
    karpenter.sh/stored-version-migrated: "true"
  name: workload-spot
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        type: spot
    spec:
      expireAfter: 240h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - t
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "4096"
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      terminationGracePeriod: 110s
  weight: 20
```

Note that I still have the annotations from migrating from 0.37.5, but the resources are currently defined in native `karpenter.sh/v1`

**Comment by JeppeButhler** [comment]
Might be seeing something like it with (currently specifically) an r8x.large instance that gets nicely filled with pods but never seems to get scaled down / consolidated to other machines (the pods are not utilizing the available resources very well, CPU usage around 5% and memory 15% - no spikes). Have had occurrences of having the same large instance for days without any disruption. We have spot-to-spot consolidation activated.

```
 Type    Reason            Age                  From       Message
 ----    ------            ----                 ----       -------  
 Normal  Unconsolidatable  17m (x3 over 47m)  karpenter  Can't remove without creating 2 candidates
```

Versions:
k8s: 1.30
karpenter: 1.0.8

Nodepool definitions:
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: service-pool
  annotations:
    kubernetes.io/description: "General purpose NodePool for services"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["eu-north-1a", "eu-north-1b"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r", "t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: prod
      expireAfter: 72h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m

---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: job-pool
  annotations:
    kubernetes.io/description: "General purpose NodePool for jobs"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64", "arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["eu-north-1a", "eu-north-1b"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r", "t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: prod
      expireAfter: 72h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
```
