### ISSUE TITLE
Unclear log line during forceful node deletion

### ISSUE THREAD

**Issue by punkwalker** [kubernetes-sigs/karpenter#1498]
### Description

**Observed Behavior**:
The node was forcefully deleted respecting `terminationGracePeriod` and ignoring blocking PDB.
During this the consistency check failure was recorded in the log without any clear error.
```
{"level":"ERROR","time":"2024-08-01T21:36:10.623Z","logger":"controller","message":"consistency error","commit":"87cabe1","controller":"nodeclaim.consistency","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"default-wc4nx"},"namespace":"","name":"default-wc4nx","reconcileID":"7a2a892c-403b-4fb9-83b6-58ac302e068b"}
```

**Expected Behavior**:

Not to see the log or more context to the error

**Reproduction Steps** (Please include YAML):
Create restrictive PDB which will block node deletion. Something like this:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  creationTimestamp: "2024-08-01T21:29:56Z"
  generation: 1
  name: my-pdb
  namespace: default
  resourceVersion: "22822423"
  uid: 1a384ec0-a4e8-4b28-a4b4-39577cddf4ab
spec:
  minAvailable: 5
  selector:
    matchLabels:
      app: inflate
```
Set `terminationGracePeriod`  in v1 NodePool.

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: "2824304348424741091"
    karpenter.sh/nodepool-hash-version: v3
  name: default
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 1k
  template:
    metadata: {}
    spec:
      expireAfter: 720h0m0s
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      terminationGracePeriod: 5m
```

Trigger Node deletion, either via drift or some other means

**Versions**:
- Chart Version: N/A
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.30.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4-eks-036c24b

```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
