### ISSUE TITLE
Karpenter continues to consolidate and ignores do-not-disrupt labels on pods hosted on terminating node 

### ISSUE THREAD

**Issue by wescobar-itv** [kubernetes-sigs/karpenter#1560]
### Description

**Observed Behavior**:
Karpenter is consolidating and terminating nodes that are running pods labeled with (karpenter.sh/do-not-disrupt: true) . Despite the expectation that Karpenter should respect the do-not-disrupt label and avoid terminating or replacing nodes hosting these pods. This is seen when running ephemeral jobs in jenkins . 

**Expected Behavior**:
Karpenter should recognize the do-not-disrupt label on pods, taking this into account and ensure that nodes hosting these pods are not included in any consolidation or disruption actions.  

**Reproduction Steps** (Please include YAML):
job spec is as follows 

```
    kind: Pod
    metadata:
      name: dev
      annotations:
        "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        "karpenter.sh/do-not-disrupt": "true"
    spec:
  
      tolerations:
        - key: "infra"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        infra: "true"
        kubernetes.io/arch: "amd64"

```

nodepool spec :

```
Spec:
  Disruption:
    Budgets:
      Nodes:               20%
    Consolidation Policy:  WhenUnderutilized
    Expire After:          720h
  Limits:
    Cpu:     1000
    Memory:  1000Gi
  Template:
    Metadata:
      Labels:
        Infra:       true
        Role:  karpenter-infra-spot
    Spec:
      Node Class Ref:
        API Version:  karpenter.k8s.aws/v1beta1
        Kind:         EC2NodeClass
        Name:         cp-infra-spot
      Requirements:
        Key:       karpenter.k8s.aws/instance-cpu
        Operator:  In
        Values:
          1
          2
          4
          8
          16
          32
        Key:       karpenter.k8s.aws/instance-hypervisor
        Operator:  In
        Values:
          nitro
        Key:       kubernetes.io/arch
        Operator:  In
        Values:
          amd64
        Key:       karpenter.sh/capacity-type
        Operator:  In
        Values:
          spot
        Key:       karpenter.k8s.aws/instance-category
        Operator:  In
        Values:
          c
          m
          r
          t
      Taints:
        Effect:  NoSchedule
        Key:     infra
        Value:   true
```

**Versions**:
- Chart Version: 0.37
- Kubernetes Version (`kubectl version`):  Client Version: v1.29.2,  Server Version: v1.28.11

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
