### ISSUE TITLE
Failure to delete NodeClaim (Reconciler error)

### ISSUE THREAD

**Issue by artem-nefedov** [kubernetes-sigs/karpenter#1578]
### Description

**Observed Behavior**:

When deleting NodePools, one of the NodeClaims got stuck and couldn't be deleted. The Node itself does get deleted, and is no longer shown in `get nodes` output, and the EC2 instance is terminated. 

Controller logs show an error:

> {"level":"ERROR","time":"2024-08-16T19:21:14.386Z","logger":"controller","message":"Reconciler error","commit":"5bdf9c3","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"system-6ss2w"},"namespace":"","name":"system-6ss2w","reconcileID":"ea1cb048-d9a1-41b9-95c6-2c89fca2402e","error":"removing termination finalizer, NodeClaim.karpenter.sh \"system-6ss2w\" is invalid: spec: Invalid value: \"object\": spec is immutable"}

Besides this one particular NodeClaim, other NodeClaims were deleted successfully.

Note: Karpenter is installed with webhook **disabled**.

**Expected Behavior**:

NodeClaim is deleted.

**Reproduction Steps** (Please include YAML):

1. Create the following nodeclass and 2 nodepools:

```yaml
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: myorg-default
spec:
  amiSelectorTerms:
  - alias: bottlerocket@latest
  role: KarpenterNodeRole-${CLUSTER_NAME}
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ${CLUSTER_NAME}
      kubernetes.io/role/internal-elb: "1"
  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: ${CLUSTER_NAME}
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: apps
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: system
spec:
  disruption:
    consolidateAfter: 30s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        myorg.com/system: shared
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: myorg-default
      requirements:
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "1024"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      - key: karpenter.k8s.aws/instance-memory
        operator: Gt
        values:
        - "2048"
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "1"
      taints:
      - effect: NoSchedule
        key: myorg.com/system
        value: "true"
```

2. Deploy some apps that use both nodepools (including daemonsets).
3. Delete nodepools and nodeclass.

**Versions**:
- Chart Version: v1.0.0
- Kubernetes Version (`kubectl version`): Server Version: v1.30.3-eks-2f46c53

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
