### ISSUE TITLE
Node got terminated outside the budget time window 

### ISSUE THREAD

**Issue by wufengzlw** [kubernetes-sigs/karpenter#1718]
### Description

**Observed Behavior**:

Karpenter log:
```
Sep 19 09:37:05.386 tainted node
Sep 19 09:45:44.980 deleted nodeclaim
Sep 19 09:45:44.757 deleted node
```

Our node consolidation window should be 10PM -- 6 AM (schedule config is the UTC time)

Node got terminated at 9:45, we have the budget window configure like
```
spec:
  disruption:
    budgets:
    - nodes: 10%
    - duration: 16h
      nodes: "0"
      schedule: 0 10 * * mon-fri
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata: {}
    spec:
      expireAfter: 168h0m0s
```

Not sure if the node got terminated because of expiration.
Q: If node expired outside the consolidation window, will it be terminated at once?

**Expected Behavior**:

**Reproduction Steps** (Please include YAML):

**Versions**:
- Chart Version: 1.0.1
- Kubernetes Version (`kubectl version`): v1.29.7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jigisha620** [comment]
From the disruption spec you have shared, 0 nodes should be disrupted between 10am - 2am from Monday-Friday (UTC time zone). Which time zone are these timestamps from?
```
Sep 19 09:37:05.386 tainted node
Sep 19 09:45:44.980 deleted nodeclaim
Sep 19 09:45:44.757 deleted node
```

**Comment by wufengzlw** [comment]
@jigisha620 we are in EST

**Comment by jigisha620** [comment]
Got it. Makes sense. 
Can you share a more complete set of logs or events that could help us understand why the node was terminated?

**Comment by wufengzlw** [comment]
@jigisha620 
This is the only log I got from Karpenter related to this node.

Could you check this question? If node expired outside the consolidation window, will it be terminated at once?

**Comment by wufengzlw** [comment]
@jigisha620 
Could you check this question? 
If node expired outside the consolidation window, will it be terminated at once?

**Comment by utk231** [comment]
+1 facing similar issue. Budgets are not being respected and nodes are terminated even within business hours window. 

`disruption:
  budgets:
  - nodes: "0"
    schedule: "30 13 * * mon-fri"
    duration: 12h
    reasons:
    - Drifted
    - Underutilized
  - nodes: "100%"
    reasons:
    - Empty
  - nodes: "10%"
    reasons:
    - Drifted
    - Underutilized`

Node terminated by karpenter in above 12h duration. No events emitted on cluster by karpenter showing block by budget as wel as in logs.

**Comment by jigisha620** [comment]
@utk231 Can you share the logs that say the node got tainted? Logs can also tell which controller triggered the deletion. It's possible that you are also facing something similar i.e. node was expired and got terminated.

**Comment by utk231** [comment]
@jigisha620 Please find the nodepool config and karpenter logs below

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    karpenter.sh/nodepool-hash: '5085166567790051606'
    karpenter.sh/nodepool-hash-version: v3
    karpenter.sh/stored-version-migrated: 'true'
spec:
  disruption:
    budgets:
      - duration: 12h
        nodes: '0'
        reasons:
          - Drifted
          - Underutilized
        schedule: 30 02 * * mon-fri
      - nodes: 100%
        reasons:
          - Empty
      - nodes: 50%
        reasons:
          - Drifted
          - Underutilized
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 2000
    memory: 2000Gi
  template:
    metadata:
      labels:
        intent: apps
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - m
            - c
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - m7g
            - c7g
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - m7g.xlarge
            - c7g.xlarge
            - m7g.2xlarge
            - c7g.2xlarge
        - key: karpenter.k8s.aws/instance-hypervisor
          operator: In
          values:
            - nitro
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '2'
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - ap-south-1a
            - ap-south-1b
        - key: kubernetes.io/arch
          operator: In
          values:
            - arm64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      terminationGracePeriod: 48h
  weight: 10
```

API Replicas scaled up to 10 -> 2 new nodes were launched
API Replicas scaled down to 2 -> Those 2 nodes were terminated by karpenter within business hour budget window

No events of budget blocking the termination in logs (file attached below)

[karpenter-66b55d7655-v7gph.log](https://github.com/user-attachments/files/17429978/karpenter-66b55d7655-v7gph.log)
