### ISSUE TITLE
Incorrect daemonset overhead with taints/tolerations

### ISSUE THREAD

**Issue by Pactionly** [kubernetes-sigs/karpenter#1749]
### Description

**Observed Behavior**:

When using Daemonsets with a toleration of `- operator: Exists`, and nodepools with taints configured, Karpenter doesn't appear to account for daemonset overhead accurately on the nodes, and logs the daemonset overhead as `{"pods":"0"}`.
This behavior appears to extend to kube-system daemonsets as well, such as kube-proxy.

Seemly as a result, in nodepools that allow it, Karpenter will generate smaller nodes than appropriate given the daemonset overhead, including generating nodes too small to even fit a single pod given existing overhead, which causes dramatic churning behavior.

**Expected Behavior**:

Karpenter should recognize that a toleration of `- operator: Exists` allows a daemonset to tolerate all taints and that daemonsets with this toleration _will_ schedule on tainted nodepools. This fact should be accounted for in daemonset overhead calculations to ensure node sizes are decided correctly.

**Reproduction Steps** (Please include YAML):

To replicate churning behavior,

Start with an EKS cluster with 4+ daemonsets with tolerations of `- operator: Exists`. For reference, our clusters have the following EKS daemonsets, but I'd expect others with the same taint to cause similar behavior: aws-node, ebs-csi-node, eks-pod-identity-agent, kube-proxy
Note: all of the listed daemonsets use the following toleration block
```
      tolerations:
      - operator: Exists
```

Apply a nodepool with some taint while also allowing for very small instance sizes (such as t3.nano):
```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: example-nodepool
spec:
  template:
    metadata:
      labels:
        owner: example
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: karpenter
      requirements:
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3"]
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["us-east-1a", "us-east-1b"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
      taints:
        - effect: NoExecute
          key: team
          value: example
      expireAfter: 120h
  limits:
    cpu: 100
    memory: 100Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 5m
```

Apply a pod for scheduling on the given nodepool:
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: owner
            operator: In
            values:
            - example
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "50Mi"
        cpu: "50m"
    ports:
    - containerPort: 80
  tolerations:
  - effect: NoExecute
     key: team
     value: example
```

A new node should be created for the pod, but if the pod size is small enough karpenter can select a t3.nano for it. This instance type only allows 4 pods, meaning it will fill with daemonset pods, and the nginx pod will fail to schedule. After a short time Karpenter seems to detect that the pod still hasn't scheduled. It'll create a new node, but will still select t3.nano causing the same issue. In the meantime, it'll detect the first node is empty, and will destroy it. Over time this causes significant churn and AWS config costs, and the nginx pod will never schedule.

I've also observed similar behavior at larger node sizes, presumably caused by the same root issue, but with particular memory and cpu requests from daemonsets squeezing out a large scheduling pod. However it's much easier to replicate at small pod & nodes sizes.

**Versions**:
- Chart Version: 1.0.5
- Kubernetes Version (`kubectl version`): v1.30.4-eks-a737599

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
