### ISSUE TITLE
Race condition with node startupTaints being restored

### ISSUE THREAD

**Issue by dpiddock** [kubernetes-sigs/karpenter#1772]
### Description

**Observed Behavior**:
Karpenter restores the `startupTaints` to a node if it is removed too quickly at node startup. This results in a node being unusable. Node also never reaches a ready state, so Karpenter refuses to remove it: `Cannot disrupt Node: state node isn't initialized`

From AWS CloudWatch logs insights:
* created state:
  ```
  requestObject.spec.taints.0 {"key":"ebs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  requestObject.spec.taints.1 {"key":"efs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  requestObject.spec.taints.2 {"key":"karpenter.sh/unregistered","effect":"NoExecute"}
  requestObject.spec.taints.3 {"key":"node.cloudprovider.kubernetes.io/uninitialized","value":"true","effect":"NoSchedule"}
  requestReceivedTimestamp 2024-10-22T13:21:21.946552Z
  ```
* node-controller updates some taints
* efs-csi removes its taint
  ```
  requestObject.0.op                test
  requestObject.0.path              /spec/taints
  requestObject.0.value.0.effect    NoExecute
  requestObject.0.value.0.key       ebs.csi.aws.com/agent-not-ready
  requestObject.0.value.1.effect    NoExecute
  requestObject.0.value.1.key       efs.csi.aws.com/agent-not-ready
  requestObject.0.value.2.effect    NoExecute
  requestObject.0.value.2.key       karpenter.sh/unregistered
  requestObject.0.value.3.effect    NoSchedule
  requestObject.0.value.3.key       node.kubernetes.io/not-ready
  requestObject.1.op                replace
  requestObject.1.path              /spec/taints
  requestObject.1.value.0.effect    NoExecute
  requestObject.1.value.0.key       ebs.csi.aws.com/agent-not-ready
  requestObject.1.value.1.effect    NoExecute
  requestObject.1.value.1.key       karpenter.sh/unregistered
  requestObject.1.value.2.effect    NoSchedule
  requestObject.1.value.2.key       node.kubernetes.io/not-ready
  requestReceivedTimestamp          2024-10-22T13:21:32.092879Z
  ...
  responseObject.spec.taints.0 {"key":"ebs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  responseObject.spec.taints.1 {"key":"karpenter.sh/unregistered","effect":"NoExecute"}
  responseObject.spec.taints.2 {"key":"node.kubernetes.io/not-ready","effect":"NoSchedule"}
  ```
* node-controller updates the not-ready taint
* Karpenter removes the unregistered taint but also restores the efs taint for some reason:
  ```
  requestObject.spec.taints.0 {"key":"ebs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  requestObject.spec.taints.1 {"key":"node.kubernetes.io/not-ready","effect":"NoExecute","timeAdded":"2024-10-22T13:21:34Z"}
  requestObject.spec.taints.2 {"key":"efs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  requestReceivedTimestamp 2024-10-22T13:21:38.465463Z
  ...
  responseObject.spec.taints.0 {"key":"ebs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  responseObject.spec.taints.1 {"key":"node.kubernetes.io/not-ready","effect":"NoExecute","timeAdded":"2024-10-22T13:21:34Z"}
  responseObject.spec.taints.2 {"key":"efs.csi.aws.com/agent-not-ready","effect":"NoExecute"}
  ```
* ebs removes its taint
* node-controller removes the not-ready taint
* Node never schedules pods

**Expected Behavior**:
Karpenter updates the existing taints on a node to remove `karpenter.sh/unregistered=NoExecute` without restoring startup taints removed by other controllers.

**Reproduction Steps** (Please include YAML):
This is an unpredictable race condition that is near impossible to reproduce on demand. 
Might be related to this code: https://github.com/rschalo/karpenter/blob/a652a4aa95dbe92159bb273a3b64ff8837d92660/pkg/controllers/nodeclaim/lifecycle/registration.go#L87

**Versions**:
- Chart Version: `1.0.6`
- Kubernetes Version (`kubectl version`):
   ```
   Client Version: v1.31.1
   Kustomize Version: v5.4.2
   Server Version: v1.30.4-eks-a737599
   ```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nuvme-devops** [comment]
+1

**Comment by jukie** [comment]
I think startupTaints should be moved into Kubelet flags or otherwise implemented during initial node registration with the cluster.

Another option/workaround, Node's could be labeled with `karpenter.sh/registered=false` during registration and users could set antiAffinity in their workloads to avoid scheduling there. This is a more convenient setup for users who might apply a `operator: Exists` toleration to workloads such as daemonsets and aligns with the current design as Karpenter already labels nodes with the inverse of this upon registration with Karpenter.

**Comment by dpiddock** [comment]
Startup taints are registered directly with kubelet. Which makes it even more confusing as to why Karpenter is adding/restoring them itself. You can see it from the audit log excepts above: the node object is created with the ebs and efs startup taints registered.

Example generated userdata from an AL2023 node:
```
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="//"

--//
Content-Type: application/node.eks.aws

# Karpenter Generated NodeConfig
apiVersion: node.eks.aws/v1alpha1
kind: NodeConfig
metadata:
  creationTimestamp: null
spec:
  cluster:
    apiServerEndpoint: https://[...]
    certificateAuthority: [...]
    cidr: 172.20.0.0/16
    name: k8s-test
  containerd: {}
  instance:
    localStorage: {}
  kubelet:
    config:
      clusterDNS:
      - 172.20.0.10
      maxPods: 58
      registerWithTaints:
      - effect: NoExecute
        key: ebs.csi.aws.com/agent-not-ready
      - effect: NoExecute
        key: efs.csi.aws.com/agent-not-ready
      - effect: NoExecute
        key: karpenter.sh/unregistered
    flags:
    - --node-labels="karpenter.k8s.aws/ec2nodeclass=mixed,karpenter.sh/capacity-type=on-demand,karpenter.sh/nodepool=mixed"

--//--
```

Our NodePool has, among other settings:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
spec:
  template:
    spec:
      startupTaints:
      - effect: NoExecute
        key: ebs.csi.aws.com/agent-not-ready
      - effect: NoExecute
        key: efs.csi.aws.com/agent-not-ready
```

**Comment by jukie** [comment]
The taints get added upon karpenter registration not at kubelet start. You can check the userdata to confirm but that's what I'm seeing.

**Comment by JeremyBolster** [comment]
Comment to allow assignment.
I would like to investigate / take up this issue.

**Comment by jukie** [comment]
Would this be a provider-specific issue based on how startupTaints are implemented? I'd like to work on the AWS side of this

**Comment by JeremyBolster** [comment]
So from what I can tell, the issue is coming from the following code, not from the cloud provider code.
https://github.com/kubernetes-sigs/karpenter/blob/main/pkg/controllers/nodeclaim/lifecycle/registration.go#L128

But I have yet to setup a reproducible demo. Sorry for the delay.

To share my findings so far,
The kubelet args are being set to include the labels (missing many from the nodeclaims) and taints, including the startup taints.
So the code adding the taints and startup taints during the node sync code is redundant, and I think it is a
race condition. I think it happens like this

Bad Order
1. Node is created. It includes the taints and startup taints.
2. Controller that removes startup taint schedules, runs, removes taint.
3. Karpenter syncs node, copying the startup taint from the nodeclaim.
4. Node has the taint again, and the controller does not re-remove it.
5. Pods do not schedule due to taint.

Good Order
1. Node is created. It includes the taints and startup taints.
3. Karpenter syncs node.
2. Controller that removes startup taint schedules, runs, removes taint.
4. Node no longer has the startup taints. Pods schedule.


As to whether or not this is a bug in the cloud provider or in the core code, I'm not sure. I guess this depends
on the contract between the core code and the provider code with respect to which component should be adding
the startup taints to the node. Right now, both the cloud provider and core code are both adding the startup
taint, which is causing a race condition. I personally believe that this is a bug in the core code, or at least
the solution needs to be in the core code as the race condition between the controller that is removing the
taint and the core code will persist unless the kubelet adds the taint to the node because it always adds it
*before* the controller that removes can be scheduled. I would argue *for* removing the syncing of taints from
nodeclaims to nodes to avoid any potential issues. 

I did chase down the code where the taints and startup taints are added to the kubelet args in the aws
provider as well. [For reference, it is here](https://github.com/aws/karpenter-provider-aws/blob/main/pkg/providers/amifamily/resolver.go#L244-L247).

**Comment by JeremyBolster** [comment]
I believe the above commit is a simple fix if we are okay with the providers owning the taints. If that is not a solution we are happy with, then I still need to think more on this find a solution. Stating that it is required that daemonsets either fail to schedule if the `karpenter.sh/unregistered` taint exists or that daemonsets continuously reconcile are the other two options that I can think of. They both seem un-workable as one requires users of Karpenter to have an affinity for the Karpenter label `karpenter.sh/initialized: "true"` on all daemonsets — which would be awkward for anyone looking to migrate a cluster from cluster autoscaler. Or changes would be required in several tools for the latter option, which seems very time consuming and like playing a game of wack-a-mole.

**Comment by GnatorX** [comment]
I think I agree with Jeremy on only having provider own taints. I understand we might want Karpenter core as a back-stop to align configurations but I wonder if it would be better to either 
a) Call it out as a condition / status/ event by the consistency controller
b) And/ or mark it as Drifted.

rather than attempt to sync the taints.

Like @JeremyBolster mentioned, there is no way for Karpenter to win the race consistently since Karpenter doesn't create the node object directly and it relies on kubelet self-registeration. To me that means that the responsibility and capability of Karpenter ends there because it doesn't control it. (In way I think nodes finalizer should be a kubelet configurable).

**Comment by jmdeal** [comment]
> one requires users of Karpenter to have an affinity for the Karpenter label karpenter.sh/initialized: "true" on all daemonsets — which would be awkward for anyone looking to migrate a cluster from cluster autoscaler

I think this might actually be the best short-term solution, and I think we could do it in such a way that it's not too awkward:

```yaml
kind: Pod
apiVersion: v1
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        # Only schedule to Karpenter node once it has been synced by the registration reconciler
        - matchExpressions:
          - key: karpenter.sh/registered
            operator: In
            values: ['true']
        # OR schedule to nodes not managed by Karpenter
        - matchExpressions:
          - key: karpenter.sh/nodepool
            operator: DoesNotExist 
```

Is this ideal and do I think this should be the long term solution - no. I do think we should stop syncing these taints but this is a relatively major breaking change. For the Karpenter provider, this would require a relatively painful migration for those using `amiFamily: Custom`. If we have another option, I'd prefer to see us hold off on making a breaking change until we can flesh out a better migration path. I'd also be curious to know if any of the other providers have input on this, so far I think we've only talked about this in the context of the AWS provider (cc @Bryce-Soghigian @elmiko).

The workaround I'm proposing also won't work today I believe - Karpenter doesn't support node selectors on the `karpenter.sh/registered` taint. This shouldn't be a big lift to add though.
