### ISSUE TITLE
Nodes are not drained properly on node termination

### ISSUE THREAD

**Issue by linkvt** [kubernetes-sigs/karpenter#1839]
### Description

Hi guys,

first of all thanks for the great work, I've been using Karpenter since quite some time and it is a pleasure 😀 .

I really can't believe that this is an actual issue but after checking everything multiple times  I still can't spot the issue on my side, which is why I think that this really might be a bug.
I've read the documentation, inspected my resources multiple times but everything seems as it should and as it was with Karpenter 0.x.

### **Observed Behavior**:

When a node has to be terminated, Karpenter does not stop my pods properly and just terminates the EC2 instance without draining the node.

I observed this in multiple scenarios that should all trigger a clean termination of my nodes (to my understanding):
- e.g. allowing only M instead of C instance types in the nodepool
- deleting a nodeclaim of a node manually

I even had disruption budgets violated when Karpenter threw away the instance that ran all Pods of a test Deployment.

Furthermore I saw emitted events on existing and Running pods that they are nominated to run on the new node:
```
  Normal   Started          9m48s              kubelet            Started container whoami-container
  Normal   Nominated        2m16s              karpenter          Pod should schedule on: nodeclaim/flux-system-nodepool-lb-test-app-45bq6
  Normal   Nominated        16s                karpenter          Pod should schedule on: nodeclaim/flux-system-nodepool-lb-test-app-dxvlv
  Warning  NodeNotReady     9s                 node-controller    Node is not ready
```
This seems quite strange to me, Karpenter should know that only Pending Pods can be scheduled?

A termination grace period is not set on the NodePool and does also not appear in the NodeClaim. 

Below are the logs when I deleted a NodeClaim via `kubectl delete ...`.
What you don't see in the logs is that it was immediately shown as "Shutting Down" in the AWS Web Console, it was deleted before the controller logged "deleted node" (I used `terminationGracePeriod: 1h` there for testing, no difference):
```jsonl
{"level":"INFO","time":"2024-11-25T19:55:28.685Z","logger":"controller","message":"annotated nodeclaim","commit":"901a5dc","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"flux-system-nodepool-lb-test-app-4g2nn"},"namespace":"","name":"flux-system-nodepool-lb-test-app-4g2nn","reconcileID":"c161b562-c1c9-4f34-9665-97b6527523bd","Node":{"name":"ip-10-107-110-211.eu-central-1.compute.internal"},"provider-id":"aws:///eu-central-1c/i-0bbed26474395ec00","karpenter.sh/nodeclaim-termination-timestamp":"2024-11-25T20:55:28Z"}
{"level":"ERROR","time":"2024-11-25T19:55:28.692Z","logger":"webhook","message":"http: TLS handshake error from 10.107.108.107:56170: read tcp 100.64.122.98:8443->10.107.108.107:56170: read: connection reset by peer\n","commit":"901a5dc"}
{"level":"INFO","time":"2024-11-25T19:55:28.743Z","logger":"controller","message":"tainted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-107-110-211.eu-central-1.compute.internal"},"namespace":"","name":"ip-10-107-110-211.eu-central-1.compute.internal","reconcileID":"bb604b5f-bb1e-4c53-b060-d8ff736e55a3","taint.Key":"karpenter.sh/disrupted","taint.Value":"","taint.Effect":"NoSchedule"}
{"level":"INFO","time":"2024-11-25T19:55:29.862Z","logger":"controller","message":"found provisionable pod(s)","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"8e500de1-2a98-4e78-bc8a-aa8cd894eaf9","Pods":"default/whoami-deployment-599b854969-92m99","duration":"115.733148ms"}
{"level":"INFO","time":"2024-11-25T19:55:29.862Z","logger":"controller","message":"computed new nodeclaim(s) to fit pod(s)","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"8e500de1-2a98-4e78-bc8a-aa8cd894eaf9","nodeclaims":1,"pods":1}
{"level":"INFO","time":"2024-11-25T19:55:29.875Z","logger":"controller","message":"created nodeclaim","commit":"901a5dc","controller":"provisioner","namespace":"","name":"","reconcileID":"8e500de1-2a98-4e78-bc8a-aa8cd894eaf9","NodePool":{"name":"flux-system-nodepool-lb-test-app"},"NodeClaim":{"name":"flux-system-nodepool-lb-test-app-92v77"},"requests":{"cpu":"1185m","memory":"3232Mi","pods":"5"},"instance-types":"c5.12xlarge, c5.2xlarge, c5.4xlarge, c5.9xlarge, c5.xlarge and 55 other(s)"}
{"level":"INFO","time":"2024-11-25T19:55:33.453Z","logger":"controller","message":"launched nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"flux-system-nodepool-lb-test-app-92v77"},"namespace":"","name":"flux-system-nodepool-lb-test-app-92v77","reconcileID":"6e9e07ef-e597-499a-81ca-693fab813a97","provider-id":"aws:///eu-central-1c/i-0ac794c22750e47e2","instance-type":"c5n.large","zone":"eu-central-1c","capacity-type":"on-demand","allocatable":{"cpu":"1930m","ephemeral-storage":"17Gi","memory":"4298Mi","pods":"29","vpc.amazonaws.com/pod-eni":"9"}}
{"level":"INFO","time":"2024-11-25T19:56:57.304Z","logger":"controller","message":"registered nodeclaim","commit":"901a5dc","controller":"nodeclaim.lifecycle","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"flux-system-nodepool-lb-test-app-92v77"},"namespace":"","name":"flux-system-nodepool-lb-test-app-92v77","reconcileID":"c3ab78a0-4dd8-4b43-ab73-b26dd320e6f6","provider-id":"aws:///eu-central-1c/i-0ac794c22750e47e2","Node":{"name":"ip-10-107-110-190.eu-central-1.compute.internal"}}
{"level":"INFO","time":"2024-11-25T19:57:08.424Z","logger":"controller","message":"deleted node","commit":"901a5dc","controller":"node.termination","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-107-110-211.eu-central-1.compute.internal"},"namespace":"","name":"ip-10-107-110-211.eu-central-1.compute.internal","reconcileID":"fe005569-87d6-49fd-bcae-e7c05a28a559"}
{"level":"INFO","time":"2024-11-25T19:57:08.673Z","logger":"controller","message":"deleted nodeclaim","commit":"901a5dc","controller":"nodeclaim.termination","controllerGroup":"karpenter.sh","controllerKind":"NodeClaim","NodeClaim":{"name":"flux-system-nodepool-lb-test-app-4g2nn"},"namespace":"","name":"flux-system-nodepool-lb-test-app-4g2nn","reconcileID":"96d946e9-0754-4751-a524-054cfa9628ba","Node":{"name":"ip-10-107-110-211.eu-central-1.compute.internal"},"provider-id":"aws:///eu-central-1c/i-0bbed26474395ec00"}

```

### **Expected Behavior**:

From my experience in the past and also reading the documentation about the disruption logic and especially the [Termination Controller](https://karpenter.sh/v1.0/concepts/disruption/#termination-controller) there should be an eviction where Pods are terminated. Only after Karpenter waited for the node to be "empty" (=only daemonsets) the EC2 instance should be removed.

### **Reproduction Steps** (Please include YAML):

I really hope that this helps reproducing the issue, if more infos/resources are needed I will provide them.

My deployment looks like this:

<details>
  <summary>Deployment Resources</summary>
  
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      nodeSelector:
        scheduling: lb-test-app
      tolerations:
        - operator: Exists
      terminationGracePeriodSeconds: 180
      containers:
        - name: whoami-container
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 60"]
          image: linkvt/whoami-plus:latest # image of me that contains the whoami binary with a base image containing a shell needed for the preStop hook
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            periodSeconds: 1
          resources: # way too high but used for me to trigger scheduling different nodes, feel free to reduce
            requests:
              cpu: "1"
              memory: 3Gi
            limits:
              cpu: "2"
              memory: 3Gi
      topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: whoami
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: whoami
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: whoami
```
  
</details>

The nodepool look as follows:

<details>
  <summary>Nodepool</summary>
  
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: flux-system-nodepool-lb-test-app
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 1m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 160
    memory: 640Gi
  template:
    metadata:
      annotations:
        nodepool: flux-system-nodepool-lb-test-app
      labels:
        scheduling: lb-test-app
    spec:
      expireAfter: 24h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: flux-system-nodepool-lb-test-app
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      taints:
      - effect: NoSchedule
        key: scheduling
        value: lb-test-app
```

</details>

I'm not posting the NodeClass right now as it is mostly internal and from my understanding unrelated, we use Amazon Linux 2 with no special settings. I can add the NodeClass if it helps.

### **Versions**:
- Chart Version: 1.0.7
- Kubernetes Version (`kubectl version`): `Server Version: v1.29.10-eks-7f9249a`

If there is anything else I can do/add to make this more reproducible, please let me know.

Thanks in advance!
Vincent 

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
