### ISSUE TITLE
Multiple schedule in disruption budgets don't work

### ISSUE THREAD

**Issue by nantiferov** [kubernetes-sigs/karpenter#1866]
### Description

Hi,

I'm not sure if this is expected behavior, but I don't see it mentioned in docs https://karpenter.sh/v1.0/concepts/disruption/

Basically, I want to invert logic, described here https://karpenter.sh/docs/concepts/nodepools/

```yaml
    budgets:
    - nodes: 10%
    - schedule: "0 9 * * mon-fri" # On Weekdays during business hours, don't do any deprovisioning.
      duration: 8h
      nodes: "0"
```

To have disruptions only during working hours. I tried to achieve this with something like:

```yaml
    budgets:
    - nodes: 10%
    - schedule: 0 16 * * mon-fri
      duration: 16h
      nodes: "0"
     
    - schedule: 0 0 * * sat-sun
      duration: 24h
      nodes: "0"
```

**Observed Behavior**:

Errors in karpenter logs: `{"level":"ERROR","time":"2024-12-05T14:34:31.529Z","logger":"controller","message":"detected disruption budget errors","commit":"a2875e3","controller":"disruption","namespace":"","name":"","reconcileID":"ca5962e8-d939-4453-a8be-4ca11fdf9bf4","error":"invalid disruption budgets in nodepool xxx, invariant violated, invalid cron %!s(<nil>)"}`

**Expected Behavior**:

Maybe it could be achieved differently, but end goal with this - to have disruptions only during working hours.

**Reproduction Steps** (Please include YAML):

Provided before.

**Versions**:
- Chart Version: 1.0.8
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by nantiferov** [comment]
Hmm, I might be wrong, but after some tests I think this actually provides what I want:

```yaml
    budgets:
    - schedule: "0 9 * * mon-fri" # On Weekdays during business hours, don't do any deprovisioning.
      duration: 8h
      nodes: 10%
```

Basically `nodes: 10%` moved to schedule and `nodes: "0"` removed

**Comment by nantiferov** [comment]
Hmm, tests shows that schedule I mentioned in https://github.com/kubernetes-sigs/karpenter/issues/1866#issuecomment-2520658046 actually doesn't work and disruptions are happening any time.

Maybe I'm missing something?

**Comment by jigisha620** [comment]
HI @nantiferov,
The standard cron syntax expects `day` in numerical form. The error that you have shared indicates incorrect syntax. You can use - 
```
budgets:
    - schedule: "0 9 * * 1-5" # On Weekdays during business hours, don't do any deprovisioning.
      duration: 8h
      nodes: 0
```

**Comment by nantiferov** [comment]
But from logic perspective, am I right, that this configuration should prevent Karpenter to do any disruptions outside of schedule time (working hours)?

```
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 0s
    budgets:
      - schedule: 0 8 * * 1-5 # working days and hours
        duration: 8h
        nodes: 10%
```
