### ISSUE TITLE
Support different consolidateAfter for different disruption reasons

### ISSUE THREAD

**Issue by maxsxu** [kubernetes-sigs/karpenter#2037]
### Description

**What problem are you trying to solve?**

Allow specify different consolidateAfter for different disruption reasons. 

For example:

  - Disrupt after 5m if Node is Empty
  - Disrupt after 1h if Node is Underutilized

Possible configurations:

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
spec:
  disruption:
    strategy:
    - consolidationPolicy: WhenEmpty
      consolidateAfter: 5m
    - consolidationPolicy: WhenUnderutilized 
      consolidateAfter: 1h
```

**How important is this feature to you?**

We want to quickly scale down the empty nodes, but slowly scale down the underutilized nodes.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
