### ISSUE TITLE
NodeRepair respects PDBs / terminationGracePeriodSeconds when nodepool does not have terminationGracePeriod set

### ISSUE THREAD

**Issue by andrewhibbert** [kubernetes-sigs/karpenter#2042]
### Description

**Observed Behavior**:

I'm not sure whether this is a bug or not. I see that NodeRepair works okay with a terminationGracePeriod set in the NodePool, however if it isn't set it seems to respect PDBs and terminationGracePeriodSeconds which I thought was strange:

After stopping kubelet on a node, PDB blocking:

```
Taints:             node.kubernetes.io/unreachable:NoExecute
                    karpenter.sh/disrupted:NoSchedule
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-138-100-239.eu-west-1.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Fri, 28 Feb 2025 14:55:09 +0000
Conditions:
  Type                    Status    LastHeartbeatTime                 LastTransitionTime                Reason                    Message
  ----                    ------    -----------------                 ------------------                ------                    -------
  MemoryPressure          Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  DiskPressure            Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  PIDPressure             Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  Ready                   Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  ContainerRuntimeReady   True      Fri, 28 Feb 2025 15:48:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   ContainerRuntimeIsReady   Monitoring for the ContainerRuntime system is active
  StorageReady            True      Fri, 28 Feb 2025 15:48:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   DiskIsReady               Monitoring for the Disk system is active
  NetworkingReady         True      Fri, 28 Feb 2025 15:48:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   NetworkingIsReady         Monitoring for the Networking system is active
  KernelReady             True      Fri, 28 Feb 2025 15:48:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   KernelIsReady             Monitoring for the Kernel system is active

Events:
  Type     Reason                 Age                From                       Message
  ----     ------                 ----               ----                       -------
  Warning  ContainerRuntimeReady  57m                eks-node-monitoring-agent  Newrelic-InfraRepeatedRestart: Systemd unit "newrelic-infra.service" has restarted (NRestarts 61 -> 76)
  Normal   NodeNotReady           54m                node-controller            Node ip-10-138-100-239.eu-west-1.compute.internal status is now: NodeNotReady
  Normal   MemoryPressure         54m                karpenter                  Status condition transitioned, Type: MemoryPressure, Status: False -> Unknown, Reason: NodeStatusUnknown, Message: Kubelet stopped posting node status.
  Normal   DiskPressure           54m                karpenter                  Status condition transitioned, Type: DiskPressure, Status: False -> Unknown, Reason: NodeStatusUnknown, Message: Kubelet stopped posting node status.
  Normal   PIDPressure            54m                karpenter                  Status condition transitioned, Type: PIDPressure, Status: False -> Unknown, Reason: NodeStatusUnknown, Message: Kubelet stopped posting node status.
  Normal   Ready                  54m                karpenter                  Status condition transitioned, Type: Ready, Status: True -> Unknown, Reason: NodeStatusUnknown, Message: Kubelet stopped posting node status.
  Normal   DisruptionBlocked      54m                karpenter                  Pdb "kube-system/ebs-csi-controller" prevents pod evictions
  Warning  ContainerRuntimeReady  52m                eks-node-monitoring-agent  Newrelic-InfraRepeatedRestart: Systemd unit "newrelic-infra.service" has restarted (NRestarts 76 -> 91)
  Normal   DisruptionBlocked      50m (x5 over 67m)  karpenter                  Pdb "kyverno/kyverno-reports-controller" prevents pod evictions
  Warning  ContainerRuntimeReady  47m                eks-node-monitoring-agent  Newrelic-InfraRepeatedRestart: Systemd unit "newrelic-infra.service" has restarted (NRestarts 91 -> 105)
```

terminationGracePeriodSeconds blocking:

```
Taints:             node.kubernetes.io/unreachable:NoExecute
                    karpenter.sh/disrupted:NoSchedule
                    node.kubernetes.io/unreachable:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  ip-10-138-100-239.eu-west-1.compute.internal
  AcquireTime:     <unset>
  RenewTime:       Fri, 28 Feb 2025 14:55:09 +0000
Conditions:
  Type                    Status    LastHeartbeatTime                 LastTransitionTime                Reason                    Message
  ----                    ------    -----------------                 ------------------                ------                    -------
  MemoryPressure          Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  DiskPressure            Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  PIDPressure             Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  Ready                   Unknown   Fri, 28 Feb 2025 14:54:39 +0000   Fri, 28 Feb 2025 14:55:53 +0000   NodeStatusUnknown         Kubelet stopped posting node status.
  ContainerRuntimeReady   True      Fri, 28 Feb 2025 16:08:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   ContainerRuntimeIsReady   Monitoring for the ContainerRuntime system is active
  StorageReady            True      Fri, 28 Feb 2025 16:08:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   DiskIsReady               Monitoring for the Disk system is active
  NetworkingReady         True      Fri, 28 Feb 2025 16:08:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   NetworkingIsReady         Monitoring for the Networking system is active
  KernelReady             True      Fri, 28 Feb 2025 16:08:36 +0000   Fri, 28 Feb 2025 14:28:36 +0000   KernelIsReady             Monitoring for the Kernel system is active

Events:
  Type     Reason                          Age                   From                       Message
  ----     ------                          ----                  ----                       -------
  Warning  FailedDraining                  19m (x14 over 45m)    karpenter                  Failed to drain node, 1 pods are waiting to be evicted
  Warning  ContainerRuntimeReady           4m53s (x11 over 54m)  eks-node-monitoring-agent  (combined from similar events): Newrelic-InfraRepeatedRestart: Systemd unit "newrelic-infra.service" has restarted (NRestarts 283 -> 298)
  Warning  TerminationGracePeriodExpiring  83s (x24 over 47m)    karpenter                  All pods will be deleted by 2025-02-28T15:25:53Z
  Normal   DisruptionBlocked               82s (x24 over 47m)    karpenter                  Node is deleting or marked for deletion
```

So the question is, is this a bug or are we advised to use this alongside `terminationGracePeriod` in the NodePool. Note that the reason why this is switched off is due to it hanging when nodes ended up in a broken state (kubelet not posting status due to exhausted CPU resources) and ideally I think we'd like to set this differently for each consolidation reason

**Expected Behavior**:

Removes node without `terminationGracePeriod` kicking in

**Reproduction Steps** (Please include YAML):

**Versions**:
1.2.1

- Chart Version:
- Kubernetes Version (`kubectl version`):
1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by engedaam** [comment]
@andrewhibbert Can you share the Karpenter logs around the nodes you are sharing? Can you also share the nodeclaim objects?

**Comment by andrewhibbert** [comment]
I have given you replication details, the nodes will stay up past the tolerationduration

**Comment by engedaam** [comment]
Using the reproduction steps, I was not able to reproduce the issue. When a terminationGracePeriod was not defined on my nodePool, I was able to use node repair to delete an unhealthy node that had a pod with a block PDB. Can you share you Karpenter deployment?

**Comment by cosimomeli** [comment]
Hello, I'm testing the NodeRepair feature too and I have seen the following behaviour: even if the NodePool has a `terminationGracePeriod` set, if the unhealthy node has a Pod with a terminationGracePeriodSeconds, the node termination waits for it, so if I force delete that pod, the node immediately starts the shutdown process.
Also looks like there's some race condition between the `node.health` and `node.lifecycle` controllers, so after the 30 minutes toleration, sometimes it's annotated by one or the other controller, so I can get one of these logs:
`{"level":"INFO","time":"2025-04-30T12:26:57.032Z","logger":"controller","message":"annotated nodeclaim","commit":"0871602","controller":"node.health","controllerGroup":"","controllerKind":"Node","Node":{"name":"ip-10-2-2-193.eu-south-1.compute.internal"},"namespace":"","name":"ip-10-2-2-193.eu-south-1.compute.internal","reconcileID":"cb5a7f49-2555-4213-973f-c69aaccfb60d","NodeClaim":{"name":"default-lp7wk"},"karpenter.sh/nodeclaim-termination-timestamp":"2025-04-30T12:26:57Z"}`

OR

`{"level":"INFO","time":"2025-04-30T13:57:44.566Z","logger":"controller","message":"disrupting node(s)","commit":"0871602","controller":"disruption","namespace":"","name":"","reconcileID":"653e76ee-a6b6-489b-adf0-5c297ebc8f0a","command-id":"0c1be116-cc2d-4c2f-8e55-a4d6d19d8a06","reason":"underutilized","decision":"delete","disrupted-node-count":1,"replacement-node-count":0,"pod-count":2,"disrupted-nodes":[{"Node":{"name":"ip-10-2-0-63.eu-south-1.compute.internal"},"NodeClaim":{"name":"default-2clbq"},"capacity-type":"on-demand","instance-type":"t4g.medium"}],"replacement-nodes":[]}`

After the first one, nothing happens and `terminationGracePeriod` is not respected. I've seen that line always related to nodes with slow-terminating pods.
After the second one, the normal procedure of consolidation is executed, and after the `terminationGracePeriod` of the NodePool the node is destroyed (probably this procedure will be stuck forever without terminationGracePeriod).

**Comment by aslatter** [comment]
I've been having trouble replicating. Is there some other complication I need to add-on to my setup?

This was with Karpenter 1.8.1, running the AWS-provider on EKS.

test node pool:

 <details>
  <summary>Node Pool</summary>

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: termdemo
spec:
  template:
    metadata:
      labels:
        node-pool: termdemo
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default

      taints:
        - key: example.com/termdemo
          effect: NoSchedule

      expireAfter: Never

      requirements:
        - key: "karpenter.k8s.aws/instance-size"
          operator: NotIn
          values: ["nano", "micro"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["t3", "t3a"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "kubernetes.io/os"
          operator: "In"
          values: ["linux"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
```

</details>

The following is a test command to back-date an auto-repair condition (AWS-specific - for another platform you may need to use a different condition-type and back-date period). The condition is back-dated 9 minutes, 50 seconds, so the controller should act in 10 seconds.

<details>
  <summary>Click to expand for details</summary>

```sh
NODE="$(kubectl get nodes -l node-pool=termdemo -o jsonpath='{.items[0].metadata.name}')"
NOW="$(date -u -d '590 seconds ago' +%FT%TZ)"

kubectl patch node "$NODE" \
  --subresource=status \
  --type=strategic \
  -p "{
    \"status\": {
      \"conditions\": [
        {
          \"type\": \"AcceleratedHardwareReady\",
          \"status\": \"False\",
          \"reason\": \"ManualTest\",
          \"message\": \"Simulated node monitoring agent failure\",
          \"lastHeartbeatTime\": \"${NOW}\",
          \"lastTransitionTime\": \"${NOW}\"
        }
      ]
    }
  }"
```

</details>

# auto-repair with PDB

This deployment has 4 replicas and a PDB with min-unavailable set to "1". Each replica takes 60s to come ready.

Triggering the fake condition shuts down all 4 pods after 10 seconds, ignoring the PDB.

<details>
  <summary>Workload with slow PDB</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-pdb
  namespace: default
spec:
  replicas: 4
  selector:
    matchLabels:
      app: slow-pdb
  template:
    metadata:
      labels:
        app: slow-pdb
    spec:
      nodeSelector:
        node-pool: termdemo
      tolerations:
        - key: example.com/termdemo
          operator: "Exists"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 3
      
      containers:
        - name: stubborn-app
          image: public.ecr.aws/docker/library/busybox:1.37
          command:
            - /bin/sh
            - -c
            - |
              # Trap SIGTERM and ignore it (simulates app not handling shutdown)
              trap 'echo "Received SIGTERM, ignoring..."' TERM

              echo "Pod started"
              echo "I will ignore SIGTERM and only die to SIGKILL"
              
              rm -f /tmp/ready
              echo "Starting; will become Ready in 60s"
              sleep 60
              touch /tmp/ready
              echo "Ready!"

              # Keep running forever
              while true; do
                sleep 10
                echo "Still running at $(date)"
              done
          readinessProbe:
            exec:
              command: ["sh","-c","test -f /tmp/ready"]
            periodSeconds: 2
            failureThreshold: 1
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: slow-pdb
  namespace: default
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: slow-pdb
```

</details>

# auto-repair with a long pod-termination-grace-period

This workload has a single replica with no PDB and no readiness check, but will ignore SIGTERM with a pod termination-grace-period of 10 minutes.

Running the test-disruption command also seems to tear-down the test-pod pretty much as soon as the ten-seconds passes.

<details>
  <summary>Click to expand for details</summary>

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: slow-terminate
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow-terminate
  template:
    metadata:
      labels:
        app: slow-terminate
    spec:
      nodeSelector:
        node-pool: termdemo
      tolerations:
        - key: example.com/termdemo
          operator: "Exists"
          effect: "NoSchedule"
      terminationGracePeriodSeconds: 600  # 10 minutes!
      
      containers:
        - name: stubborn-app
          image: public.ecr.aws/docker/library/busybox:1.37
          command:
            - /bin/sh
            - -c
            - |
              # Trap SIGTERM and ignore it (simulates app not handling shutdown)
              trap 'echo "Received SIGTERM, ignoring..."' TERM
              
              echo "Pod started, PID $$"
              echo "I will ignore SIGTERM and only die to SIGKILL"
              
              # Keep running forever
              while true; do
                sleep 10
                echo "Still running at $(date)"
              done
```

</details>
