### ISSUE TITLE
Karpenter does not respect eviction order in certain Disruption situations

### ISSUE THREAD

**Issue by elijah-rou** [kubernetes-sigs/karpenter#2073]
### Description

**Observed Behavior**:
Under certain disruption conditions, Karpenter does not appear to follow the default eviction order (workload Pods -> `system-cluster-critical` & `system-node-critical` workload pods -> daemonset pods -> `system-cluster-critical` & `system-node-critical` daemonset pods)

For example, if a NodePool is deleted or a NodeClaim manually deleted, resulting in the current nodes being drifted, Karpenter will drain _all_ pods (incl. ones with prio class `system-cluster-critical` & `system-node-critical`.

**Expected Behavior**:
Karpenter respects the eviction order under all disruption conditions (manually or automatically triggered, drift vs consolidation, etc.)

**Reproduction Steps** (Please include YAML):
- Create any NodePool, scheduling both a workload with no priority class and a workload with `system-node-critical` as the priority class. EG:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: non-prio
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodepool
                operator: In
                values:
                  - nodepool_a
  containers:
    - image: busybox
      command: ["tail", "-f", "/dev/null"]
      name: non-prio
---
apiVersion: v1
kind: Pod
metadata:
  name: prio
spec:
  priorityClass: system-node-critical
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: nodepool
                operator: In
                values:
                  - nodepool_a
  containers:
    - image: busybox
      command: ["tail", "-f", "/dev/null"]
      name: prio
---
apiVersion: karpenter.sh/v1
kind: NodePool
  name: nodepool-a
spec:
  disruption:
    budgets:
      - nodes: 60%
    consolidateAfter: 120s
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: 32
    memory: 64Gi
  template:
    metadata:
      labels:
        nodepool: nodepool_a
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: system
      requirements:
        - key: node.kubernetes.io/instance-type
          operator: In
          values:
            - t3a.large
            - t3.large
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
      terminationGracePeriod: 30s
```
- Delete either the NodeClaim created for the workloads, or just delete the NodePool
- Observe Karpenter puts `karpenter.sh/disrupted` on the node
- All workloads evict without respecting order

**Versions**:
- Chart Version: 1.3.1
- Kubernetes Version (`kubectl version`): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
