### ISSUE TITLE
expire node using cron expression

### ISSUE THREAD

**Issue by bhavasarpritesh** [kubernetes-sigs/karpenter#2076]
### Description

**What problem are you trying to solve?**
expireAfter field only support specifying number values in s,m,h unit and but if we want to expired node only during less peak hour at that time expireAfter isn't useful so if we add support for cron as well then we can specify cron expression which will expire node at less peak hour, eg every sunday night 1am
**How important is this feature to you?**
this feature will help to expire node at the specified time only properly and will give fine grain control over node expiry
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
I would be hesitant to surface something like this. The advantages are pretty obvious, but I think the drawbacks are a more subtle. This would result in all nodes for a given NodePool being forcibly disrupted simultaneously. In my opinion, that's a massive footgun and without an extremely strong justification I'm not sure it's worth the risk. If you have such a justification, please let us know.

Generally speaking though, I would push you away from using expiration as the standard mechanism for recycling nodes. Drift is usually the more appropriate mechanism, and drift can be time constrained via disruption budgets.

**Comment by arbazkhn** [comment]
I’d like to add my perspective and support for more granular control of expireAfter behavior.

Right now, I want to use expireAfter to recycle nodes only during predefined maintenance windows,  for example, every Saturday between 9 AM and 5 PM ET. While disruption budgets work great for Drifted and Underutilized scenarios, expireAfter bypasses them entirely, which makes this kind of scheduling impossible.

It would be extremely useful if:

- `expireAfter` could respect `disruption.budgets`, just like other disruption types
- Or alternatively, we had a new disruption reason: Expired, so it could be explicitly controlled with budgets

Here’s an example of the type of behavior I’d like to achieve:

```
disruption:
  consolidationPolicy: WhenEmptyOrUnderutilized
  consolidateAfter: 10m
  budgets:
    # Block Drifted, Underutilized, and Expired disruptions Sunday to Friday
    - schedule: "0 0 * * sun-fri"
      duration: 24h
      reasons:
        - Drifted
        - Underutilized
        - Expired
      nodes: "0"

    # Allow disruptions only on Saturday 9 AM–5 PM ET (14:00–22:00 UTC)
    - schedule: "0 14 * * sat"
      duration: 8h
      reasons:
        - Drifted
        - Underutilized
        - Expired
      nodes: "1"

```
