### ISSUE TITLE
Node does not deleted after expiration lifetime

### ISSUE THREAD

**Issue by maltez** [kubernetes-sigs/karpenter#2077]
### Description

**Observed Behavior**:
We had 8 GPU nodes in the pool that had been running for almost three weeks. They had to be terminated by Karpenter since there were no active pods on them.
Karpenter tried to terminate one exact node (log is from the controller):
```
disrupting nodeclaim(s) via delete, terminating 1 nodes (0 pods) node/g4dn.2xlarge/on-demand
tainted node
```
 
After that nothing happened with the node or EC2 instance (it had been in running state since then) because there was no API call to terminate the instance (it's not present in CloudTrail logs). It's unknown why there was no API call.
 
Another issue is that all other 7 nodes weren't terminated and Karpenter didn't try to do that. All other nodes were terminated by Karpenter only after stuck EC2 was terminated manually, node was manually removed from the cluster and nodeclaim was removed by Karpenter.
 
**Expected Behavior**:
 
- API call to terminate EC2 instance was made.
- All other 7 nodes from the pool were terminated by Karpenter even after it failed to remove one node from the pool before.
 
**Reproduction Steps** (Please include YAML):
```
    apiVersion: karpenter.sh/v1
    kind: NodePool
    metadata:
      name: gpu
    spec:
      template:
        metadata:
          labels:
            node_type: gpu
        spec:
          nodeClassRef:
            name: gpu
            group: karpenter.k8s.aws
            kind: EC2NodeClass
          requirements:
            - key: node.kubernetes.io/instance-type
              operator: In
              values: ["g4dn.2xlarge", "g4dn.4xlarge", "g4dn.8xlarge"]
            - key: topology.kubernetes.io/zone
              operator: In
              values: ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
            - key: karpenter.sh/capacity-type
              operator: In
              values: ["on-demand"]
          taints:
            - key: nvidia.com/gpu
              effect: NoSchedule
      limits:
        cpu: 256
        memory: "500Gi"
      disruption:
        consolidationPolicy: WhenEmpty
        consolidateAfter: 30s
```
 
There should be at least two nodes in the node pool, both of them should be in the state when Karpenter should terminate them. The hardest part is to reproduce missing first API call to terminate one of instances (reasons of this issue are unknown).
 
**Versions**:
- Chart Version: 1.0.8
- Kubernetes Version (`kubectl version`): 1.31
 
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
