### ISSUE TITLE
`Too many pods` on nodes does not trigger scaling up

### ISSUE THREAD

**Issue by MikeJansen** [kubernetes-sigs/karpenter#2080]
### Description

**Observed Behavior**:

Karpenter does not scale up if pods are pending due to `Too many pods`.

**Expected Behavior**:

If nodes have `Too many pods`, that condition should be detected as a node not being scheduleable and if there are no other nodes available and one or more pods are pending, a new node should be provisioned.

**Reproduction Steps** (Please include YAML):

1. Create an `EC2NodeClass` with `spec.kubelet.podsPerCore: 14`.
```yaml
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: defaultpool
spec:
  amiSelectorTerms:
  - alias: al2023@latest
  kubelet:
    podsPerCore: 14
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
  role: <<<a role>>>
  securityGroupSelectorTerms:
  - tags:
      kubernetes.io/cluster/<<<a cluster>>>: owned
  subnetSelectorTerms:
  - tags:
      aws-cdk:subnet-type: Private
```
2. Create a `NodePool` that uses that `EC2NodeClass` and only allows `large` instance sizes.  This will have 2 vCPU which will allow 28 pods with the `EC2NodeClass` settings above.
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: defaultpool
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 0s
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: defaultpool
      requirements:
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - large
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - c
        - m
        - r
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
```

3. Create a lightweight deployment
```yaml
kind: Deployment
metadata:
  name: busybox-loop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox-loop
  template:
    metadata:
      labels:
        app: busybox-loop
    spec:
      containers:                                
      - name: busybox                            
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Busybox is running...'; sleep 30; done"]
```

4. Slowly scale up and watch the number of pods successfully go up to 28 (taking into account any daemonsets or other pods running).
5. When the pod count would go to 29 on the node, watch the pod remain pending with an event entry of something similar to:
> FailedScheduling  42m   default-scheduler  0/1 nodes are available: 1 Too many pods 
 6. Note that no new node is scheduled.

**Versions**:
- Chart Version: **1.3.0**
- Kubernetes Version (`kubectl version`):
   Client Version: v1.32.3
   Kustomize Version: v5.5.0
   Server Version: v1.31.5-eks-8cce635

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
