### ISSUE TITLE
Karpenter scale out infinitely when a pod use host port already used

### ISSUE THREAD

**Issue by Reasonably** [kubernetes-sigs/karpenter#2083]
### Description

**Observed Behavior**:
- Karpenter trigger scale up infinitely

<img width="695" alt="Image" src="https://github.com/user-attachments/assets/90e76e75-8541-4b5b-b5f5-902ec47553e7" />

![Image](https://github.com/user-attachments/assets/36115202-ebae-453f-9d7f-30a7fd6111dc)

**Expected Behavior**:

- do not trigger scale up, just show event like Cluster Autoscaler

![Image](https://github.com/user-attachments/assets/4d3b8578-9c0b-4f37-bb9b-c08e3c140129)

**Reproduction Steps** (Please include YAML):
1. deploy daemonset which uses hostport `x`
2. deploy deployment which uses hostport `x`
3. the pod cannot schedule because of no free port, but karpenter trigger scale up continously

1. daemonset
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-test
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: daemon-test
  template:
    metadata:
      labels:
        name: daemon-test
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: daemon-test
        image: nginx
        ports:
        - name: web
          containerPort: 80
          hostPort: 8080
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi

```

2. deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          hostPort: 8080
```

**Versions**:
- Chart Version:  20.24.0
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.32.2
Kustomize Version: v5.5.0
Server Version: v1.31.6-eks-bc803b4
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
