### ISSUE TITLE
podsPerCore not being honoured

### ISSUE THREAD

**Issue by andy-cowley** [kubernetes-sigs/karpenter#2111]
### Description

**Observed Behavior**:

- Create an `EC2NodeClass` that specifies `podsPerCore` in the Kubelet config of 2
- Start a Job with 300 replicas
- All 300 land on a `c6a.16xlarge` which has 64 cores or similar - either way, we exceed 2 pods per core

Have tested this extensively and Karpenter seems to ignore `podsPerCore` and schedule pods based on the limit from the ENI no matter what.

Docs point to [this reference](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1/) but v1 has no mention or concept of any of this, whereas [v1beta1](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration) does.

**Expected Behavior**:

A node with 64 cores runs a maximum of 128 pods

**Reproduction Steps** (Please include YAML):

Job

```
apiVersion: batch/v1
kind: Job
metadata:
  name: xx
  namespace: xx
spec:
  backoffLimit: 0
  completionMode: NonIndexed
  completions: 300
  manualSelector: false
  parallelism: 300
  podFailurePolicy:
    rules:
    - action: Ignore
      onExitCodes:
        operator: NotIn
        values:
        - 0
  podReplacementPolicy: Failed
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-disrupt: "true"
      creationTimestamp: null
    spec:
      containers:
        envFrom:
        - configMapRef:
            name:xx
        - secretRef:
            name: xx
        image: xx
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        securityContext:
          runAsGroup: 1000
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/resim
          name: working
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - sh
        - -c
        - '[ "$(stat -c ''%u:%g'' $WORKING_DIR)" = "1000:1000" ] || chown -R 1000:1000
          $WORKING_DIR || true'
        env:
        - name: WORKING_DIR
          value: /tmp/resim
        image: public.ecr.aws/docker/library/busybox:stable
        imagePullPolicy: IfNotPresent
        name: chowner
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp/resim
          name: working
      nodeSelector:
        resim.io/on-demand: "true"
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      serviceAccount: xx
      serviceAccountName: xx
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: resim.io/on-demand
        operator: Exists
      volumes:
      - name: working
        persistentVolumeClaim:
          claimName: xx
  ttlSecondsAfterFinished: 7200
```

NodeClass

```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
spec:
  amiFamily: Bottlerocket
  amiSelectorTerms:
  - alias: bottlerocket@latest
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 20Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 250Gi
      volumeType: gp3
  instanceProfile: xxx
  kubelet:
    podsPerCore: 2
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: xxx
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: xxx
```

NodePool

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: test
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidateAfter: 5m0s
    consolidationPolicy: WhenEmpty
  template:
    spec:
      expireAfter: Never
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
```

**Versions**:
- Chart Version: 1.33
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.6-eks-bc803b4
Kubecolor Version: 0.4.0
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
