### ISSUE TITLE
Karpenter underprovisions CPU requests for DS with certain node affinity

### ISSUE THREAD

**Issue by jeremysprofile** [kubernetes-sigs/karpenter#2116]
### Description

**Observed Behavior**:

Karpenter provisions a Node with too little allocatable CPU for the Pod and DS it needs to schedule.

**Expected Behavior**:

Karpenter accurately takes into account all DS that will end up being scheduled on the Node it will create.

**Reproduction Steps** (Please include YAML):

Create a NodePool, DaemonSet, and Deployment by `kubectl apply -f` on the files in the comment below.
See that Karpenter logs a too-low CPU request value and provisions a Node that cannot hold the Deployment and DaemonSet together, and either the Pod of the Deployment or the Daemonset will be stuck Pending.
(If the Deployment is stuck Pending, Karpenter will provision another new too-small Node and repeat. If the DaemonSet is stuck Pending, you'll only have one Node.)

See the Karpenter logs in the comment below.

If you remove the 
```yaml
              - key: karpenter.sh/registered
                operator: In
                values:
                - "true"
```
from the DaemonSet affinity, Karpenter will accurately take into account the DaemonSet resources and provision a large enough Node.

This seems similar to (but the reverse of) https://github.com/kubernetes-sigs/karpenter/issues/715

**Versions**:
- Chart Version: v0.32.10 (yes, we're very behind)
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jeremysprofile** [comment]
Deployment YAML:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jeremy-deploy
  labels:
    label1: oldvalue
spec:
  replicas: 1
  selector:
    matchLabels:
      jeremy: jeremy-deploy
  template:
    metadata:
      labels:
        jeremy: jeremy-deploy
    spec:
      tolerations:
      - key: nodepool
        operator: Equal
        value: jeremytest
        effect: NoSchedule
      nodeSelector:
        karpenter.sh/nodepool: jeremytest
      containers:
      - name: jeremy-pod
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
            memory: "5Gi"
          limits:
            memory: "5Gi"
```

DaemonSet YAML:

```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: daemonset
    app.kubernetes.io/instance: jeremy-ds
    app.kubernetes.io/name: jeremy
  name: jeremy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: daemonset
      app.kubernetes.io/instance: jeremy-ds
      app.kubernetes.io/name: jeremy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: daemonset
        app.kubernetes.io/instance: jeremy-ds
        app.kubernetes.io/name: jeremy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: karpenter.sh/registered
                operator: In
                values:
                - "true"
              - key: karpenter.sh/nodepool
                operator: In
                values:
                - jeremytest
      containers:
      - image: nginx:latest
        imagePullPolicy: IfNotPresent
        name: jeremy-ds
        resources:
          requests:
            cpu: "7"
            memory: "1Gi"
          limits:
            cpu: "7"
            memory: "1Gi"
      tolerations:
      - operator: Exists
```

NodePool YAML:

```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: jeremytest
spec:
  disruption:
    consolidateAfter: 15m
    consolidationPolicy: WhenEmpty
    expireAfter: 24h
  template:
    metadata:
      labels:
        cluster-name: dev-ats-v2
        nodepool: ats
    spec:
      kubelet:
        clusterDNS:
        - 192.168.0.10
        kubeReserved:
          cpu: 500m
          ephemeral-storage: 3Gi
          memory: 500Mi
        systemReserved:
          cpu: 500m
          ephemeral-storage: 1Gi
          memory: 500Mi
      nodeClassRef:
        name: default
      requirements:
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - m
        - c
        - r
      - key: karpenter.k8s.aws/instance-cpu
        operator: Gt
        values:
        - "3"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "5"
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - 2xlarge
        - 4xlarge
        - 8xlarge
        - 9xlarge
        - 12xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
        - arm64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      taints:
      - effect: NoSchedule
        key: nodepool
        value: jeremytest
```
