### ISSUE TITLE
Support MatchLabelKeys in podAffinity/podAntiAffinity

### ISSUE THREAD

**Issue by igorcalabria** [kubernetes-sigs/karpenter#2124]
### Description

**What problem are you trying to solve?**

Hi, I'm trying to ensure that dynamically provisioned pods with common label ends up on a single AZ. This could be achieved with something like this 

```yml
spec:
  template:
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: spark-role
                operator: In
                values:
                - executor
            topologyKey: topology.kubernetes.io/zone
            matchLabelKeys:
            - spark-app-selector
 ```
Each job will request a bunch of pods with a common label `spark-app-selector=<uid-here>`. This affinity definition will ensure that for a given job, all of its executors will end up on the same AZ. I could use a simple labelSelector by explicitly setting the spark-app-selector (it's normally automatically generated) but that's super clunky in this context. 

MatchLabels in podAffinity graduated to beta in k8s 1.3.1: https://kubernetes.io/blog/2024/08/16/matchlabelkeys-podaffinity/
