### ISSUE TITLE
Karpenter not choosing the cheapest overall option

### ISSUE THREAD

**Issue by andreambrosioBS** [kubernetes-sigs/karpenter#2150]
### Description

**Observed Behavior**:

Not sure if this is a problem in karpenter-aws-provider or kapenter in general, but I can change this issue if necessary

We are migrating from cluster autoscaler to karpenter, and we were expecting to have some cost savings and a better utilization of resources.
With cluster autoscaler we had 4 r6a.4xlarge instances that were not being fully utilized.
After migrating to karpenter we ended up with 1 r6a.4xlarge and 8 c6a.2xlarge.

Looking at the karpenter metrics for pricing
r6a.4xlarge=1.0152$/h
c6a.2xlarge=0.32832/h

Cluster autoscaler cost = 4*1.0152=4.0608
Karpenter cost = 1.0152 + 8*0.32832=3.64176

We see indeed a cost savings here. However looking at the utilization of our nodes we see 

<img width="266" alt="Image" src="https://github.com/user-attachments/assets/5a090947-ccae-4e33-8807-667a4dad7055" />

c6a.2xlarge instances have 8 vcpus and 16GiB of memory
r6a.2xlarge instances have 8 vpcus and 64GB of memory

Since most c6a.2xlarge instances have an utilization of around 80% requested memory and 25%/30% requested cpu, I would expect most of the c6a instances would be consolidated in one R or even M instance that are cheaper than 2 C instances.

Looking at the node events these are the two events that I see

```
Events:
  Type    Reason            Age                  From       Message
  ----    ------            ----                 ----       -------
  Normal  Unconsolidatable  117s (x54 over 13h)  karpenter  Can't remove without creating 2 candidates
```
And this one
```
Events:
  Type    Reason            Age                   From       Message
  ----    ------            ----                  ----       -------
  Normal  Unconsolidatable  2m19s (x56 over 14h)  karpenter  Can't replace with a cheaper node
```

**Expected Behavior**:

Karpenter would consolidate nodes with higher utilization, and choose a node configuration that overall would be cheaper, instead of just looking at individual nodes.

1 r6a.2xlarge instance is 0.5076 that is cheaper than 2 c6a.2xlarge that is 2 * 0.32832 = 0,65664

**Reproduction Steps** (Please include YAML):

Nodepool

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: >-
      karpenter-bitsight-development-eu-west-1:karpenter.sh/NodePool:karpenter/default
    kubernetes.io/description: Default NodePool for generic workloads
  labels:
    argocd.argoproj.io/instance: karpenter-bitsight-development-eu-west-1
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - r
            - m
            - c
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values:
            - '4'
        - key: karpenter.k8s.aws/instance-size
          operator: NotIn
          values:
            - medium
            - large
            - xlarge
```

Ec2nodeclass
```
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        deleteOnTermination: true
        encrypted: true
        volumeSize: 100Gi
        volumeType: gp3
  kubelet:
    maxPods: 500
  metadataOptions:
    httpPutResponseHopLimit: 2
  role: >-
    arn:aws:iam::xxxxx:role/role-name
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster-name
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: cluster-name
```

**Versions**:
- Chart Version:  [1.3.2](https://github.com/aws/karpenter-provider-aws/blob/main/charts/karpenter/Chart.yaml)
- Kubernetes Version (`kubectl version`): 1.31

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
