### ISSUE TITLE
Cannot select multiple zones

### ISSUE THREAD

**Issue by daimaxiaxie** [kubernetes-sigs/karpenter#2152]
### Description

**Observed Behavior**:

pod pending, nodeclaim still selects the fault domain.

**Expected Behavior**:

nodeclaim can select the normal domain.

**Reproduction Steps** (Please include YAML):

Zone B:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
     name: default-B
spec:
    template:
        spec:
            nodeClassRef:
                group: karpenter.k8s.alibabacloud
                kind: ECSNodeClass
                name: default-B               # only use zone b vswitch(subnet)
            requirements:
             - key: karpenter.k8s.alibabacloud/instance-family
                operator: In
                values:
                - ecs.g7                             # zone B has not g7 instance
```
Zone M:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
     name: default-M
spec:
    template:
        spec:
            nodeClassRef:
                group: karpenter.k8s.alibabacloud
                kind: ECSNodeClass
                name: default-M               # only use zone M vswitch(subnet)
            requirements:
             - key: karpenter.k8s.alibabacloud/instance-family
                operator: In
                values:
                - ecs.g7                      
```

pod:
```yaml
apiVersion: apps/v1
kind: Deployment
spec:
    replicas: 1
    template:
       spec:
           topologySpreadConstraints:
           - labelSelector:
              matchLabels:
                   app: name
              maxSkew: 1
              topologyKey: topology.kubernetes.io/zone
              whenUnsatisfiable: DoNotSchedule 
```

Then Karpenter schedule requirement zone in B. But default-M not match. 

```bash
{"level":"ERROR","time":"2025-04-18T10:56:47.251Z","logger":"controller","caller":"provisioning/provisioner.go:350","message":"could not schedule pod","commit":"fca0e55","controller":"provisioner","namespace":"","name":"","reconcileID":"7fece4f2-5b7c-4d0d-acf2-a11149216475","Pod":{"name":"app-7ffbcbb5c5-8vcvn","namespace":"default"},"error":"incompatible with nodepool \"default-M\", daemonset overhead={\"cpu\":\"500m\",\"memory\":\"500Mi\",\"pods\":\"1\"}, no instance type satisfied resources {\"cpu\":\"3500m\",\"memory\":\"3572Mi\",\"pods\":\"2\"} and requirements karpenter.k8s.alibabacloud/ecsnodeclass In [default-m], karpenter.k8s.alibabacloud/instance-family In [ecs.g7], karpenter.sh/nodepool In [default-M], kubernetes.io/arch In [amd64], kubernetes.io/os In [linux], topology.kubernetes.io/zone In [cn-shanghai-b] (no instance type met the scheduling requirements or had a required offering)"}
```

At this time, we expect the pod to be scheduled to zone M. (requirement zone in M)

**Versions**:
- Chart Version:
- Kubernetes Version (`kubectl version`): 1.28

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
