### ISSUE TITLE
Karpenter does not scale the cluster when the pod was a preferred node affinity for a given hostname

### ISSUE THREAD

**Issue by rodrigorfk** [kubernetes-sigs/karpenter#2181]
### Description

**Observed Behavior**:

When deploying Karpenter with `preferencePolicy=Ignore`, I would expect that any `preferredDuringSchedulingIgnoredDuringExecution` added to pod would be considered as a soft constraint and Karpenter would still scale the cluster if such pod is marked as unschedulable by the kube-scheduler.

However, Karpenter is still ignoring some pods, depending of the `key` used in the `matchExpressions` even if `preferencePolicy=Ignore` is defined, essentially not scaling the cluster further. 

**Expected Behavior**:

If Karpenter is running with `preferencePolicy=Ignore`, I would expect that pending pods flagged as unschedulable by the kube-scheduler would trigger Karpenter provisioning capabilities.

**Reproduction Steps** (Please include YAML):

Assuming a deployment like the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-info-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: pod-info-test-1
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pod-info-test-1
    spec:
      containers:
        - name: pod-info-test-1
          image: "ghcr.io/stefanprodan/podinfo:6.8.0"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 8
              memory: 16Gi
            requests:
              cpu: 8
              memory: 16Gi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ip-10-0-0-1.eu-west-1.compute.internal
            weight: 100
```
And assuming that there is no enough spare capacity in the cluster for a pod with 8 cpus to be scheduled, once the pod is created, it will stuck in Pending state.

**Versions**:
- Chart Version: v1.4.0
- Kubernetes Version (`kubectl version`): v1.30.11

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
