### ISSUE TITLE
karpenter didnt respect disruption budget schedule for Drift

### ISSUE THREAD

**Issue by yovio-rca** [kubernetes-sigs/karpenter#2183]
### Description

**Observed Behavior**: I have a NodePool with YAML listed in reproduction steps. 
As per my understanding, the nodepool has disruption budget
1. Allow disrupting 35% of my nodes for all reason (Empty, underutilized, drift) during this schedule: Monday 1AM - 5AM
2. Allow disrupting 35% of my node if Empty at any time.

This morning (Thursday 9:50 AM Central or 14:50 UTC) there is a new BottleRocket release 1.37.0 and it caused a Drift and Karpenter replaced nodes in NodePool ouside the schedule.

I saw NodeClaim events: Disrupting NodeClaim: Drifted/Replace

**Expected Behavior**:

Karpenter should not disrupt my node wventhough it detect Drift, because its outside the schedule, instead it should wait until Monday 1AM UTC.

**Reproduction Steps** (Please include YAML):

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: core-app
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-category"
          operator: In
          values: ["m", "r"]
        - key: "karpenter.k8s.aws/instance-family"
          operator: In
          values: ["r8g","r7g","m8g","m7g"]
        - key: "karpenter.k8s.aws/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
        - key: "karpenter.k8s.aws/instance-generation"
          operator: Gt
          values: ["5"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]
      taints:
        - effect: NoSchedule
          key: core-app
          value: "true"
      expireAfter: 720h # Nodes expire after 30 days if no drift occurs
    metadata:
      labels:
        core-app: "true"
  limits:
    cpu: 100
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 15m
    budgets:
      - nodes: "35%" # Allow 35% nodes to be disrupted during the window
        schedule: "0 1 * * 1" # Start at 1 AM UTC on early monday (This is around 6/7 PM Central Time)
        duration: 4h # Allow disruptions for 6 hours
        reasons:
          - Drifted
          - Underutilized
          - Empty
      - nodes: "35%" # Allow disrupting 35% nodes if empty
        schedule: "* * * * *" # Applies all the time
        duration: 24h
        reasons:
          - Empty

**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`): 1.32

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jmdeal** [comment]
Budgets have the opposite semantic - rather than the default being 0 and budgets allowing disruption, the default is 100% and budgets are used to restrict disruption during their specified window. In this case, your budget allows 100% disruption normally, and 35% disruption during the schedule window. To achieve what you're looking for, you would need to set a baseline budget of 35%, and a budget of 0 nodes when disruption is disallowed.

/kind support
/triage solved

**Comment by yovio-rca** [comment]
So I should specify like this ?

spec:
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 15m
    budgets:
      - nodes: "35%" # Allow 35% nodes to be disrupted during the window
        schedule: "0 1 * * 1" # Start at 1 AM UTC on early monday (This is around 6/7 PM Central Time)
        duration: 4h # Allow disruptions for 6 hours
        reasons:
          - Drifted 
          - Underutilized
          - Empty
      - nodes: "35%" # Allow disrupting 35% nodes if empty
        schedule: "* * * * *" # Applies all the time
        duration: 24h
        reasons:
          - Empty

      - nodes: 0

**Comment by jmdeal** [comment]
Not quite, since you have a budget of 0 with no schedule, that is always your most restrictive budget. This means that disruption would never be allowed. This should be what you want:
```yaml
budgets:
# At any given time, at most 35% of nodes may be disrupted
- nodes: 35% 
# Restrict the budget to 0 nodes for drift and underutilization on Sunday and Tuesday-Saturday
- nodes: 0
  reasons:
  - Drifted
  - Underutilized
  schedule: "0 0 * * 0,2-6"
  duration: 24h
# Restrict the budget to 0 until 1:00 UTC on Mondays for drift and underutilization
- nodes: 0
  reasons:
  - Drifted
  - Underutilized
  schedule: "0 0 * * 1"
  duration: 1h
# Restrict the budget to 0 from 5:00 UTC onwards on Mondays for drift and underutilization
- nodes: 0
  reasons:
  - Drifted
  - Underutilized
  schedule: "0 5 * * 1"
  duration: 19h
```
Disruption budgets were designed to restrict disruption at specific times rather than allow disruption. They're capable of modeling both, but allowing disruption at a given time is a little more awkward.
