### ISSUE TITLE
Karpenter not honoring reason in NodePool

### ISSUE THREAD

**Issue by jicowan** [kubernetes-sigs/karpenter#2202]
### Description

**Observed Behavior**: Karpenter immediately replaces instances when it detects that the node claims have drifted from the EC2NodeClass rather than replacing them according to the schedule that I set. I think this may be related to #1691.

**Expected Behavior**: Karpenter should wait to replace the instances until the appointed time (0 0 * * 0), every Sun at midnight. 

**Reproduction Steps** (Please include YAML): 

_NodePool configuration_
```yaml
spec:
  disruption:
    budgets:
      - duration: 1h
        nodes: 10%
        reasons:
          - Drifted
        schedule: 0 0 * * 0
      - nodes: 20%
        reasons:
          - Underutilized
          - Empty
    consolidateAfter: 30s
    consolidationPolicy: WhenEmpty
```

_Original EC2NodeClass_
```yaml
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
```

_New EC2NodeClass_
```yaml
spec:
  amiFamily: AL2023
  amiSelectorTerms:
    - id: ami-007672b66bd72c80f
```

**Versions**:
- Chart Version: 1.02
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jicowan** [comment]
I upgraded to Karpenter 1.4.0 and see the same behavior. I also notice that when I add an AMI to the EC2NodeClass the existing instances get replaced immediately. Until I remove the old AMI from the amiSelectorTerms, I expect the existing instances to continue running. Instances added after the update to the EC2NodeClass should use the new AMI.

**Comment by mariuskimmina** [comment]
There seems to be a misunderstanding in how schedules work, looking at your budget

```
    budgets:
      - duration: 1h
        nodes: 10%
        reasons:
          - Drifted
        schedule: 0 0 * * 0
      - nodes: 20%
        reasons:
          - Underutilized
          - Empty
```

I think what this mean is that:
At the time of `schedule` Karpenter will only disrupt `nodes` percentage of nodes  with `reason` at a time for `duration`

Since there is no budget defined for the rest of the time, karpenter is free disrupt as many drifted nodes at a time as it pleases (while respecting PDBs).

**Comment by jicowan** [comment]
Thanks @mariuskimmina. I got it to work by using the following configuration: 

```yaml
      # replace 10% of the nodes at a time within this 1hr window (midnight to 1AM)
      - nodes: "10%"
        reasons:
          - Drifted
        schedule: "0 0 * * 0"
        duration: 1h

      # Block drifted node replacements at all other times
      - nodes: "0"
        reasons:
          - Drifted
        schedule: "0 1 * * 0"  
        duration: 167h
```
