### ISSUE TITLE
All AZ domains included in topology spread constraints evaluation even when nodepool restricts to specific AZs

### ISSUE THREAD

**Issue by Reasonably** [kubernetes-sigs/karpenter#2227]
### Description

# All AZ domains included in topology spread constraints evaluation even when nodepool restricts to specific AZs

**Observed Behavior**:
When scheduling pods with topology spread constraints, Karpenter evaluates constraints against all availability zones known to the cluster, not just the ones defined in the nodepool being used. In my case, I have a nodepool "x" that explicitly restricts to 3 AZs (us-east-1a, us-east-1b, us-east-1c), and I use nodeSelector in my pods to explicitly target only this nodepool. However, the error message shows that Karpenter is considering all 6 AZs (a-f) in its topology calculations:

```
"incompatible with nodepool \"x\", daemonset overhead={\"cpu\":\"330m\",\"memory\":\"420Mi\",\"pods\":\"8\"}, unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = us-east-1a: 2, us-east-1b: 2, us-east-1c: 2, us-east-1d: 0, us-east-1e: 0, us-east-1f: 0, podDomains = topology.kubernetes.io/zone Exists, nodeDomains = topology.kubernetes.io/zone In [us-east-1a us-east-1b us-east-1c]"
```

The issue specifically occurs because I have other nodepools in the same cluster that do NOT have zone constraints. Karpenter aggregates domain information from all nodepools, so even though my target nodepool only allows 3 zones, the domain group includes all 6 zones from the unconstrained nodepools.

**Expected Behavior**:
When pods use nodeSelector to target a specific nodepool, Karpenter should only consider the AZs defined in that nodepool for topology spread constraint calculations. In this case, only us-east-1a, us-east-1b, and us-east-1c should be considered, since those are the only zones allowed by the nodepool "x" that the pod is explicitly targeting.

**Reproduction Steps** (Please include YAML):
1. Have multiple nodepools in a cluster, with at least one nodepool that does not restrict AZs (this is key to reproducing the issue)
2. Create a nodepool with specific AZ restrictions:

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: x
spec:
  template:
    metadata:
      labels:
        node.pubg.io/management-class: general
        node.pubg.io/node-type: x
        node.pubg.io/platform: linux
        nodeType: x
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values:
            - c7gn
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-east-1a
            - us-east-1b
            - us-east-1c
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
      taints:
        - effect: NoSchedule
          key: nodeType
          value: x
```

3. Deploy pods with topology spread constraints and nodeSelector targeting this nodepool:

```yaml
nodeSelector:
  nodeType: x
```

**Versions**:
- Chart Version: 1.3.2
- Kubernetes Version (`kubectl version`): v1.31

Looking at the code in `pkg/controllers/provisioning/scheduling/topology.go`, it appears that the `buildDomainGroups` function combines domain information from all nodepools into a single shared domain group. This causes topology spread constraints to be evaluated against all domains known to the cluster, not just the ones defined in the specific nodepool being used.
