### ISSUE TITLE
Pods using Restricted Node Labels don't scale up nodes

### ISSUE THREAD

**Issue by BojanZelic** [kubernetes-sigs/karpenter#2230]
### Description

**Observed Behavior**:
Pods that contain reserved node labels in their selection affinity selection cause karpenter to not scale up new nodes for the workload and the pods are stuck in `Pending`

**Expected Behavior**:
Because the `nodeSelectorTerms` is an OR statement, the inclusion of a single reserved node label shouldn't prevent scaling up. In the example below we try to schedule to a node with `node-role.kubernetes.io/my-node-role: true` OR `kubernetes.io/arch: amd64` yes no scale up is observed. 

**Reproduction Steps** (Please include YAML):

Deploy this yaml, observe that karpenter doesn't create a new nodeclaim
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karpenter-test-deployment
  namespace: spinnaker
  labels:
    app.kubernetes.io/name: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/my-node-role
                operator: In
                values:
                - "true"
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "6"
            memory: "12Gi"
          limits:
            memory: "12Gi"
```
**Versions**:
- Chart Version: 1.3.3
- Kubernetes Version (`kubectl version`): 1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
