### ISSUE TITLE
6 min wait time is still happening for statefulset when nodes are replaced by karpenter

### ISSUE THREAD

**Issue by balusarakesh** [kubernetes-sigs/karpenter#2237]
### Description

**Observed Behavior**: We are noticing a 6 minute wait time when nodes are drained by karpenter. This only seems to happen when karpenter drains the pods, if we manually drain the nodes this doesn't happen.

**Expected Behavior**: Statefulset volumes should be unmounted when nodes are drained by karpenter.

**Reproduction Steps** (Please include YAML):
Based on my observation this happens only on some nodes and not all nodes drained by karpenter. We have 4 nodes and I made karpenter drain them by switching the AMIs multiple times and noticed that roughly half of them have this issue and the other half do not.
I have the following config setup as well:

on the ebs-csi-node daemonset I set `terminationGracePeriodSeconds: 60`

userdata on EKS nodes:
```
      #!/bin/bash
      echo "$(jq '.shutdownGracePeriod="90s"' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json
      echo "$(jq '.shutdownGracePeriodForCriticalPods="75s"' /etc/kubernetes/kubelet/kubelet-config.json)" > /etc/kubernetes/kubelet/kubelet-config.json

```

NodePool:
```
- apiVersion: karpenter.sh/v1beta1
  kind: NodePool
  metadata:
    name: default
  spec:
    template:
      spec:
        terminationGracePeriod: 30m
        nodeClassRef:
          name: default
        requirements:
          - key: node.kubernetes.io/instance-type
            operator: In
            values: [c6a.8xlarge, c5a.4xlarge]
          - key: "karpenter.sh/capacity-type"
            operator: In
            values: ["on-demand"]
        kubelet:
          systemReserved:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: 1Gi
          kubeReserved:
            cpu: 200m
            memory: 100Mi
            ephemeral-storage: 3Gi
          evictionMaxPodGracePeriod: 120
    disruption:
      consolidationPolicy: WhenEmpty
      consolidateAfter: 2m
      expireAfter: 720h
      budgets: 
      - nodes: 5%
    limits:
      cpu: "1000"
      memory: 1000Gi

```
**How to reproduce:**
- create a few statefulsets with EBS volumes attached
 - change AMI on the NodeClass to make karpenter drain the nodes and check on the new statefulset pods that are restarted

<img width="572" alt="Image" src="https://github.com/user-attachments/assets/72af4aed-84c6-4467-b28f-b5211b738784" />

**Versions**: karpenter version `1.1.2`
- Chart Version: `public.ecr.aws/karpenter v0.34.0`
- Kubernetes Version (`kubectl version`):
```
Client Version: v1.32.2
Server Version: v1.31.7-eks-bcf3d70
```

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
