### ISSUE TITLE
Karpenter and its ConsolidateAfter config does not work Optimally for Empty Nodes

### ISSUE THREAD

**Issue by Adityashar** [kubernetes-sigs/karpenter#2254]
### Description

**Observed Behavior**:

When we perform a large and a sudden deployment, Karpenter has a habit of over-provisioning nodes or creating more nodeClaims that what are actually required. Eg: If we deploy a simple app with 50 pods, then Karpenter will provisioner twice or thrice the count of actually required nodes, eg, 20-25 new nodes while our original 50 pods deployment gets scheduled only on 10 nodes.

Now, we also have another requirement where we want to make use of the `consolidateAfter` flag (say 25min) in the same nodePool. With the above behaviour (of over-provisioned nodes), we are now wasting a lot of resources and cloud costs since 10-15 "completely empty" nodes remain in our K8s clusters until this time duration of 25 mins is hit and Karpenter decides to terminate them.

**Expected Behavior**:

1. Empty nodes should be excluded from the consolidateAfter configuration. We needed this flag to prevent nodes (with newly created pods) from consolidating / disruption. But empty nodes, especially the duplicate nodeClaims, should not wait until the end of this time period.
2. Duplicate NodeClaims are not created. This is a temporary concern right now, since their lifetime is mostly 2-3mins.

**Reproduction Steps** (Please include YAML):

I can add these steps if needed, please let me know.

**Versions**:
- Chart Version: v1.09
- Kubernetes Version (`kubectl version`): v1.30

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Adityashar** [comment]
Thank you for your response, @jonathan-innis!

> I can think of just off the top of my head is if you are using preferences in your pod spec

I believe this is the reason why I saw that unexpected provisioning of nodes when I first did this experiment. We inject a podAntiAffinity with the "preferred" clause in all of our pods to ensure that least number of pods belonging to the same application get deployed on the same node.

To verify the above (that excess provisioning is not happening in a case **without** "preferences"), I performed the same experiment again. 

The deployment and nodepool used here are as follows:

<details>
<summary>deployment.yaml</summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-do-not-disrupt
  namespace: test-do-not-disrupt
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: sample-do-not-disrupt
  template:
    metadata:
      namespace: test-do-not-disrupt
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: sample-do-not-disrupt
    spec:
      containers:
        - name: test
          image: <image>
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 1500m
              memory: 2Gi
            requests:
              cpu: 1500m
              memory: 2Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        karpenter.k8s.aws/instance-size: 4xlarge
        karpenter-specialised-group-name: general-limited-disruption-temp
      serviceAccountName: test-do-not-disrupt
      serviceAccount: test-do-not-disrupt
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
      - key: karpenter-specialised-group-name
        operator: Equal
        value: general-limited-disruption-temp
        effect: NoSchedule
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
```

</details>

<details>
<summary>nodepool.yaml</summary>

```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  labels:
    karpenter-provisioner-type: specialised
    karpenter-specialised-group-name: general-limited-disruption-temp
  name: specialised-provisioner-general-limited-disruption-temp
spec:
  disruption:
    budgets:
      - nodes: 10%
        duration: 50m
        schedule: "0 0 * * *" # Dummy
        reasons:
          - Underutilized
          - Drifted
      - nodes: 100%
        reasons:
          - Empty
    consolidateAfter: 25m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        karpenter-provisioner-type: specialised
        karpenter-specialised-group-name: general-limited-disruption-temp
    spec:
      expireAfter: 1728000s
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: specialised-provisioner-general-limited-disruption-template
      requirements:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
        - key: topology.kubernetes.io/zone
          operator: In
          values:
            - us-east-1a
            - us-east-1b
            - us-east-1c
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
            - arm64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
            - spot
        - key: karpenter.k8s.aws/instance-size
          operator: In
          values:
            - 4xlarge
            - 6xlarge
            - 8xlarge
            - 9xlarge
            - 10xlarge
            - 12xlarge
            - 16xlarge
            - 18xlarge
            - 24xlarge
            - 32xlarge
            - 48xlarge
        - key: karpenter.k8s.aws/instance-category
          operator: NotIn
          values:
            - t
            - a
            - x
            - h
        - key: karpenter.k8s.aws/instance-family
          operator: NotIn
          values:
            - c1
            - cc1
            - cc2
            - cg1
            - cg2
            - cr1
            - c3
            - r3
            - g1
            - g2
            - hi1
            - hs1
            - m1
            - m2
            - m3
            - t1
        - key: karpenter.k8s.aws/instance-generation
          operator: NotIn
          values:
            - '1'
            - '2'
            - '3'
            - '4'
      taints:
        - effect: NoSchedule
          key: karpenter-specialised-group-name
          value: general-limited-disruption-temp
```

</details>

---
On creating this deployment with 1 replica, I saw 3 nodes being provisioned by Karpenter, 2 nodes being completely empty:
```bash
> kubectl get pod -n test-do-not-disrupt
NAME                                   READY   STATUS    RESTARTS   AGE
test-do-not-disrupt-64466fccfb-8w6j6   2/2     Running   0          6m49s

> kubectl get nodes -l 'karpenter-specialised-group-name=general-limited-disruption-temp' -o custom-columns='NAME:.metadata.name,STATUS:.status.conditions[-1].type,AGE:.metadata.creationTimestamp,INSTANCE-TYPE:.metadata.labels.node\.kubernetes\.io\/instance-type,ZONE:.metadata.labels.topology\.kubernetes\.io\/zone'
NAME                           STATUS   AGE                    INSTANCE-TYPE   ZONE
ip-10-74-20-141.ec2.internal   Ready    2025-05-30T12:41:30Z   c6g.4xlarge     us-east-1a
ip-10-74-57-12.ec2.internal    Ready    2025-05-30T12:42:00Z   c6g.4xlarge     us-east-1a
ip-10-74-60-223.ec2.internal   Ready    2025-05-30T12:41:02Z   c6g.4xlarge     us-east-1a
 ~~
```
---
On creating this deployment with 75 replicas, I saw 14 nodes being provisioned by Karpenter:
```bash
> kubectl get pod -n test-do-not-disrupt --no-headers | wc -l
      75

> kubectl get nodes -l 'karpenter-specialised-group-name=general-limited-disruption-temp' -o custom-columns='NAME:.metadata.name,STATUS:.status.conditions[-1].type,AGE:.metadata.creationTimestamp,INSTANCE-TYPE:.metadata.labels.node\.kubernetes\.io\/instance-type,ZONE:.metadata.labels.topology\.kubernetes\.io\/zone'
NAME                            STATUS   AGE                    INSTANCE-TYPE   ZONE
ip-10-74-0-80.ec2.internal      Ready    2025-05-30T13:04:10Z   c6g.4xlarge     us-east-1a
ip-10-74-1-192.ec2.internal     Ready    2025-05-30T13:04:06Z   c6g.4xlarge     us-east-1a
ip-10-74-100-177.ec2.internal   Ready    2025-05-30T13:04:36Z   c6g.4xlarge     us-east-1b
ip-10-74-13-144.ec2.internal    Ready    2025-05-30T13:04:33Z   c6g.4xlarge     us-east-1a
ip-10-74-20-141.ec2.internal    Ready    2025-05-30T12:41:30Z   c6g.4xlarge     us-east-1a
ip-10-74-31-129.ec2.internal    Ready    2025-05-30T13:04:48Z   c6g.4xlarge     us-east-1a
ip-10-74-38-168.ec2.internal    Ready    2025-05-30T13:04:35Z   c6g.4xlarge     us-east-1a
ip-10-74-51-206.ec2.internal    Ready    2025-05-30T13:04:04Z   c6g.4xlarge     us-east-1a
ip-10-74-52-120.ec2.internal    Ready    2025-05-30T13:04:55Z   c6g.4xlarge     us-east-1a
ip-10-74-63-135.ec2.internal    Ready    2025-05-30T13:04:08Z   c6g.4xlarge     us-east-1a
ip-10-74-69-77.ec2.internal     Ready    2025-05-30T13:04:04Z   c6g.4xlarge     us-east-1b
ip-10-74-72-244.ec2.internal    Ready    2025-05-30T13:04:05Z   c6g.4xlarge     us-east-1b
ip-10-74-75-252.ec2.internal    Ready    2025-05-30T13:04:04Z   c6g.4xlarge     us-east-1b
ip-10-74-85-58.ec2.internal     Ready    2025-05-30T13:04:07Z   c6g.4xlarge     us-east-1b
```
These 75 pods got scheduled on 9 nodes in total, while the remaining 5 were left as empty:
```bash
> kubectl get pod -n test-do-not-disrupt -o wide --no-headers | awk '{print $7}' | sort | uniq
ip-10-74-0-80.ec2.internal
ip-10-74-1-192.ec2.internal
ip-10-74-20-141.ec2.internal
ip-10-74-51-206.ec2.internal
ip-10-74-63-135.ec2.internal
ip-10-74-69-77.ec2.internal
ip-10-74-72-244.ec2.internal
ip-10-74-75-252.ec2.internal
ip-10-74-85-58.ec2.internal
```

Has such behavior of excess node provisioning by Karpenter been noticed before? What would your suggestion be to reduce it?
