### ISSUE TITLE
Stale metric series for operator_status_condition_count served up

### ISSUE THREAD

**Issue by schahal** [kubernetes-sigs/karpenter#2273]
### Description

**Observed Behavior**:

The metric `operator_status_condition_count`served up by the controller pod at `:8000/metrics` seem to get in 
stale state after 24-48 hours of the operator continuously running.

For example, I get this series being scraped:

```
operator_status_condition_count{group="karpenter.sh",kind="NodeClaim",name="foobar-w7qnn",namespace="",reason="StartupTaintsExist",status="Unknown",type="Initialized"} 1
```

**Workaround:** After restarting the pod/controller, that metric is not served.

**Expected Behavior**:

Despite that metric, the NodeClaim is in fact ready/healthy and initialized:

```
$ kubectl get nodeclaim foobar-w7qnn -o jsonpath='{.status.conditions[?(@.type=="Initialized")]}' | jq .
{
  "lastTransitionTime": "2025-05-31T15:32:49Z",
  "message": "",
  "observedGeneration": 1,
  "reason": "Initialized",
  "status": "True",
  "type": "Initialized"
}
```

When the controller is restarted, that metric series is not returned (in fact, it looks like the entire metric is not returned, so I'm not sure when it's regenerated/re-served... maybe when a new nodeclaim is created? Which seems like a bug as well?).

**Reproduction Steps** (Please include YAML):

Intermittent... but generally:

1. Ensure v1.5.0 of controller is running for at least a couple days
2. Then see if a NodePool can create NodeClaim in your cluster:

<details><summary>Click to see sample NodePool which would then own the NodeClaim</summary>

```
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  annotations:
    <redacted>
  name: foobar
spec:
  disruption:
    budgets:
    - duration: 18h
      nodes: "0"
      reasons:
      - Drifted
      - Underutilized
      schedule: 0 10 * * mon-fri
    consolidateAfter: 5m
    consolidationPolicy: WhenEmptyOrUnderutilized
  template:
    metadata:
      labels:
        baz.com/disk-type: ebs
        baz.com/provisioner: karpenter
        baz.com/type: foobar
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default-foo
      requirements:
      - key: karpenter.k8s.aws/instance-hypervisor
        operator: In
        values:
        - nitro
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
        - amd64
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - spot
        - on-demand
      startupTaints:
      - effect: NoSchedule
        key: cni.istio.io/not-ready
      taints:
      - effect: NoSchedule
        key: my.provisioner
        value: karpenter
      - effect: NoSchedule
        key: baz.com/type
        value: test
  weight: 10
```
</details>

**Versions**:
- Chart Version: v1.5.0 (controller version)
- Kubernetes Version (`kubectl version`): v1.32.3-eks-bcf3d7

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
