### ISSUE TITLE
Nodes Disrupted Outside Scheduled Window

### ISSUE THREAD

**Issue by pijain** [kubernetes-sigs/karpenter#2329]
### Description

**Observed Behavior**:
We have a Karpenter NodePool with disruption budgets defined, including a scheduled disruption window for the Underutilized reason. However, we’re observing that nodes are being disrupted outside the defined schedule.

Additionally, nodes with a single high-memory pod (e.g., 24Gi out of 32Gi) are still being marked as underutilized rather than fully utilized or non-empty.

Karpenter Logs:
```
{"level":"INFO","time":"2025-06-22T17:36:58.825Z","logger":"controller","message":"disrupting node(s)","reason":"underutilized","decision":"delete","disrupted-node-count":1,"pod-count":1}
{"level":"INFO","time":"2025-06-22T17:36:59.679Z","logger":"controller","message":"tainted node","taint.Key":"karpenter.sh/disrupted"}
{"level":"INFO","time":"2025-06-22T17:43:35.214Z","logger":"controller","message":"deleted nodeclaim","NodeClaim":{"name":"<masked>"}} 
```

**Expected Behavior**:

- Nodes should only be disrupted for the Underutilized reason during the scheduled window.
- Nodes with a single high-memory pod (e.g., 75% of node memory requested) should not be marked underutilized unless criteria are clearly defined.

**Reproduction Steps** (Please include YAML): 
Here is a simplified version of the NodePool configuration:
```yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: gpu-g6
spec:
  disruption:
    budgets:
      - duration: 4h
        nodes: 10%
        reasons: [Drifted]
        schedule: 0 4 1-7 1,4,7,10 1
      - duration: 4h
        nodes: 10%
        reasons: [Underutilized]
        schedule: 0 4 * * *
      - nodes: 70%
        reasons: [Empty]
    consolidateAfter: 30m
    consolidationPolicy: WhenEmptyOrUnderutilized
  limits:
    cpu: '1000'
    memory: 5000Gi
  template:
    spec:
      expireAfter: 720h
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: al2023
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: [amd64]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: [g6.2xlarge]
        - key: karpenter.sh/capacity-type
          operator: In
          values: [on-demand]
      taints:
        - effect: NoSchedule
          key: nvidia.com/gpu
          value: 'true'
  weight: 25
```

**Versions**: 
- Chart Version: 1.5.0
- Kubernetes Version (`kubectl version`): 1.32 eks

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Nklya** [comment]
I'm not part of Karpenter team, but I think there might be issue in schedule itself. 

It seems explicit deny of disruption is missing, please check this issue for details https://github.com/kubernetes-sigs/karpenter/issues/1939#issuecomment-2628533814

**Comment by pijain** [comment]
@Nklya thanks for your response, initially i tried

```yaml
spec:
  disruption:
    budgets:
      - nodes: 0
      - duration: 4h
        nodes: 10%
        reasons: [Drifted]
        schedule: 0 4 1-7 1,4,7,10 1
      - duration: 4h
        nodes: 10%
        reasons: [Underutilized]
        schedule: 0 4 * * *
      - nodes: 70%
        reasons: [Empty]
```

But then it was not consolidating at all, and reading through karpenter's documentation. It appeared like it was always picking nodes 0 as most restrictive.

> For multiple budgets in a NodePool, Karpenter will take the minimum value (most restrictive) of each of the budgets.

**Comment by Nklya** [comment]
> It appeared like it was always picking nodes 0 as most restrictive.

Yep, you need to limit 0 with schedule.

**Comment by jigisha620** [comment]
>disruption:
    budgets:
      - duration: 4h
        nodes: 10%
        reasons: [Drifted]
        schedule: 0 4 1-7 1,4,7,10 1
      - duration: 4h
        nodes: 10%
        reasons: [Underutilized]
        schedule: 0 4 * * *
      - nodes: 70%
        reasons: [Empty]

The budget that you have provided allows 10% underutilized nodes to be disrupted between 04:00-08:00 everyday. And the log line indicates that the underutilized node was disrupted at "2025-06-22T17:36:58.825Z" which seems like the right behavior. Because outside of that window, disruption of underutilized nodes is allowed. If that's not what you want, you will have to change the disruption budget accordingly.

**Comment by pijain** [comment]
The time in the logs is UTC already, and it was happening at 17UTC, which is outside the scheduled window.

**Comment by mariuskimmina** [comment]
> The time in the logs is UTC already, and it was happening at 17UTC, which is outside the scheduled window.

Yes, it's outside the scheduled window which means the 10% limitation does not apply. Since there is no other budget applying to underutilized disruptions in this configuration, Karpenter is free to disrupt as many nodes as it pleases during this time (while honoring other constraints such as PDBs).

I believe what you want is something like this:

```
spec:
  disruption:
    budgets:
      - duration: 4h
        nodes: 10%
        reasons: [Underutilized]
        schedule: 0 4 * * *
      - duration: 20h
        nodes: 0
        reasons: [Underutilized]
        schedule: 0 8 * * *
```

I do agree with https://github.com/kubernetes-sigs/karpenter/issues/2387 that Karpenters disruption budgets are often confusing and the documentation for them is not that great.
