### ISSUE TITLE
Support Limits for Static/Local PersistentVolumes

### ISSUE THREAD

**Issue by alec-rabold** [kubernetes-sigs/karpenter#545]
### Description

**What problem are you trying to solve?**

Karpenter isn't able to detect when a [local volume](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) won't mount to an existing node due to insufficient PersistentVolumes. Because of this, workarounds like `antiAffinity` on `kubernetes.io/hostname` are needed in order to force scheduling:
```YAML
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                  - my-app
            topologyKey: "kubernetes.io/hostname"
```

It'd be great if Karpenter could detect the availability of local PVs for existing nodes. 

**How important is this feature to you?**

This gap creates significant scheduling & coordination challenges across applications.

---

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
