### ISSUE TITLE
Node Repair

### ISSUE THREAD

**Issue by jbouricius** [kubernetes-sigs/karpenter#750]
**Tell us about your request**
Allow a configurable expiration of NotReady nodes.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I am observing some behavior in my cluster where occasionally nodes fail to join the cluster, due to some transient error in the kubelet bootstrapping process. These nodes stay in NotReady status. Karpenter continues to assign pods to these nodes, but the k8s scheduler won't schedule to them, leaving pods in limbo for extended periods of time. I would like to be able to configure Karpenter with a TTL for nodes that failed to become Ready. The existing configuration `spec.provider.ttlSecondsUntilExpiration` doesn't really work for my use case because it will terminate healthy nodes.

**Are you currently working around this issue?**
Manually deleting stuck nodes.

**Additional context**
Not sure if this is useful context, but I observed this error on one such stuck node. From `/var/log/userdata.log`:
```
Job for sandbox-image.service failed because the control process exited with error code. See "systemctl status sandbox-image.service" and "journalctl -xe" for details.
```
and then `systemctl status sandbox-image.service`:
```
  sandbox-image.service - pull sandbox image defined in containerd config.toml
   Loaded: loaded (/etc/systemd/system/sandbox-image.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2022-06-28 18:47:42 UTC; 2h 9min ago
  Process: 4091 ExecStart=/etc/eks/containerd/pull-sandbox-image.sh (code=exited, status=2)
 Main PID: 4091 (code=exited, status=2)
```
From reading others issues it looks like this AMI script failed, possibly in the call to ECR: https://github.com/awslabs/amazon-eks-ami/blob/master/files/pull-sandbox-image.sh

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by hitsub2** [comment]
In my case, When provided the kubelet args(currently not supported by Karpenter), some nodes(2 out of 400) are not ready and karpenter can not disrupt them, leaving them forever. After changing AMIFamily to Custom, this issue does not happend again.

**Comment by tip-dteller** [comment]
Hi, ive been referred to this ticket and adding the case we've hit.

### Description

**Observed Behavior**:
Background:
Windows application deployed on Karpenter Windows Nodes - Ami family 2019, **OnDemand** nodes.
When the application becomes unresponsive and enters CrashLoopBackOff, its breaks containerd 1.6.18.
The given error is:
```
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open //./pipe/containerd-containerd: The system cannot find the file specified."
```
* Side note: AWS recently updated Windows containerd from 1.6.8 to 1.6.18. 

Why does it matter for this case and how its relevant to Karpenter?

The node was created and _**was functional, it was in "Ready"**_ state as noted by Karpenter and the Windows pods were successfully scheduled onto it. So far so good.
When the application unexpectedly broke containerd and subsequently kubelet, the node enters "NotReady" state.
During this cycle, 

At this point, the node is not deprovisioned and prompts this in the events:
```
karpenter  Cannot deprovision Node: Nominated for a pending pod
```

Summary of events:
1. Deploy Windows application
2. Application is in Pending mode.
3. Karpenter provisions a functional windows node.
4. Application loads and enters Running state (its functional).
5. Application breaks containerd after N time.
6. Node is unresponsive.
7. Karpenter cannot deprovision the node because Old pods terminated and New pods are Pending.


**Expected Behavior**:

Detect that the node is unresponsive and roll it (i.e create a replacement node).

**Reproduction Steps** (Please include YAML):
Provisioner:
```
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: windows-provisioner
spec:
  consolidation:
    enabled: false
  limits:
    resources:
      cpu: 200
  labels:
    app: workflow
  ttlSecondsAfterEmpty: 300
  taints:
    - key: "company.io/workflow"
      value: "true"
      effect: "NoSchedule"
  requirements:
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: ["c", "m", "r"]
    - key: "karpenter.k8s.aws/instance-cpu"
      operator: In
      values: ["4", "8", "16", "32", "48", "64"]
    - key: "karpenter.k8s.aws/instance-generation"
      operator: Gt
      values: ["4"]
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: ["us-east-1a", "us-east-1b"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type" 
      operator: In
      values: ["on-demand"] 
    - key: kubernetes.io/os
      operator: In
      values: ["windows"]

  providerRef:
    name: windows
```

I cannot provide the windows application as it entails business logic.

-- I Couldnt anything in Karpenter documentation that states this is normal behavior and I hope for some clarity here.

**Versions**:
- Chart Version:  v0.31.0
- Kubernetes Version (`kubectl version`): Server Version: v1.24.17-eks-f8587cb, Client Version: v1.28.3
