### ISSUE TITLE
Pods failed to schedule in two NodePool configuration

### ISSUE THREAD

**Issue by disparo13** [kubernetes-sigs/karpenter#932]
### Description

**Observed Behavior**: I needed to create two NodePool configurations with different `consolidationPolicy` settings, but my workload pods failed to schedule on the NodePool for which they were intended. The second NodePool can schedule pods successfully if they have toleration to the pool's node taint. In the pending pod's description, I see this:

```
  Normal   Nominated         108s (x12 over 24m)  karpenter          Pod should schedule on: nodeclaim/default-cvkcv, node/ip-10-199-71-41.ec2.internal
  Warning  FailedScheduling  77s (x3 over 4m14s)  default-scheduler  0/8 nodes are available: 1 Insufficient memory, 1 node(s) didn't find available persistent volumes to bind, 2 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}, 4 node(s) had untolerated taint {im-a-sparklike: true}. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
```

**Expected Behavior**: Karpenter should claim extra nodes to ensure workload Pods schedule

**Reproduction Steps** (Please include YAML):

**Versions**: 
- Chart Version: 0.33.1
- Kubernetes Version (`kubectl version`): Server Version: v1.27.8-eks-8cb36c9

Deploy Karpenter to the Fargate, then create such Karpenter's configuration:

```
---
# Source: karpenter/templates/ec2nodeclass.yaml
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: Bottlerocket
  role: dev-karpenter-node-role
  subnetSelectorTerms:
    - tags:
        Name: "dev-private*"
        Environment: "dev"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "dev"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 10Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeSize: 40Gi
        volumeType: gp3
        encrypted: true
        deleteOnTermination: true
---
# Source: karpenter/templates/nodepool.yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: default
spec:
  template:
    metadata:
      labels:
        instance-group: default
        pod-type: permanent
    spec:
      kubelet:
        maxPods: 110
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - t
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "2"
        - "4"
        - "8"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
  limits:
    cpu: 250
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 168h
  weight: 20
---
# Source: karpenter/templates/nodepool.yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: sparklike
spec:
  template:
    metadata:
      labels:
        instance-group: sparklike
        pod-type: sparklike
    spec:
      kubelet:
        maxPods: 110
      nodeClassRef:
        name: default
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - t
      - key: karpenter.k8s.aws/instance-cpu
        operator: In
        values:
        - "2"
        - "4"
        - "8"
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "2"
      startupTaints:
      - effect: NoExecute
        key: node.cilium.io/agent-not-ready
        value: "true"
      taints:
      - effect: NoSchedule
        key: im-a-sparklike
        value: "true"
  limits:
    cpu: 250
  disruption:
    consolidateAfter: 20m
    consolidationPolicy: WhenEmpty
    expireAfter: 168h
  weight: 10
```

I'm using Cilium, so I must also deploy Cilium with the aws-cni layered configuration, but I use no any network policy. 
Then I create a workload to schedule on a `sparklike` NodePool

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "500Mi"
      nodeSelector:
        pod-type: "sparklike"
      tolerations:
      - key: "im-a-sparklike"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
             - labelSelector:
                 matchExpressions:
                   - key: "app"
                     operator: In
                     values:
                     - nginx
               topologyKey: "kubernetes.io/hostname"
```
This Deployment is scheduling its pods without a problem. 

At the next step I'm using a `bitnami/wordpress` Helm chart to deploy a workload for the `default` NodePool

`helm install wordpress bitnami/wordpress --version 18.1.8 -n default`

and so those pods, intended to be scheduled at the default NodePool couldn't be scheduled

```
 default              wordpress-764fb9bb78-kp88z                ●          0/1           Pending                           0 n/a                     n/a                                            56m             │
│ default              wordpress-mariadb-0                       ●          0/1           Pending                           0 n/a                     n/a                                            56m             
```

with those strings in description:

```
  Warning  FailedScheduling  6m17s (x5 over 23m)  default-scheduler  0/9 nodes are available: 1 Insufficient memory, 1 node(s) didn't find available persistent volumes to bind, 2 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}, 5 node(s) had untolerated taint {im-a-sparklike: true}. preemption: 0/9 nodes are available: 1 No preemption victims found for incoming pod, 8 Preemption is not helpful for scheduling..
  Normal   Nominated         108s (x12 over 24m)  karpenter          Pod should schedule on: nodeclaim/default-cvkcv, node/ip-10-199-71-41.ec2.internal
  Warning  FailedScheduling  77s (x3 over 4m14s)  default-scheduler  0/8 nodes are available: 1 Insufficient memory, 1 node(s) didn't find available persistent volumes to bind, 2 node(s) had untolerated taint {eks.amazonaws.com/compute-type: fargate}, 4 node(s) had untolerated taint {im-a-sparklike: true}. preemption: 0/8 nodes are available: 1 No preemption victims found for incoming pod, 7 Preemption is not helpful for scheduling..
```

What else - I have two nodes scheduled for the 'default' NodePool, which runs only Cilium's pods, but Karpenter cannot claim any extra nodes to run my workloads and is not undertaking anything.

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
