### ISSUE TITLE
Empty nodepools do not report usage metrics or have a status

### ISSUE THREAD

**Issue by mattsre** [kubernetes-sigs/karpenter#935]
### Description

**Observed Behavior**:
I have a nodepool responsible for autoscaling nodes to run tasks. When no tasks are needing to be run, the nodepool scales to 0 nodes. While there are 0 nodes in the pool, the nodepool does not have a status and does not report the `karpenter_nodepool_usage` metric. This causes some issues with monitoring, as alerts setup to monitor usage notify on no data whenever the nodepool scales to 0 nodes.

**Expected Behavior**:
While there are 0 nodes in the pool, I would expect the nodepool to show a status as follows:
```json
{
    "resources": {
      "cpu": "0",
      "ephemeral-storage": "0Ki",
      "memory": "0Ki",
      "pods": "0"
    }
}
```

I would also expect it to report the `karpenter_nodepool_usage` metric with a 0 for the relevant resource types.

**Reproduction Steps** (Please include YAML):
1. Create a nodepool with disruption/consolidation enabled and a taint to only allow specific workloads to run on these nodes:
```yaml
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: tasks-nodepool
spec:
  template:
    spec:
      requirements:
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values:
            - c
            - m
            - r
            - t
        - key: karpenter.k8s.aws/instance-cpu
          operator: In
          values:
            - "4"
            - "8"
            - "16"
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - spot
            - on-demand
      nodeClassRef:
        name: default
      taints:
        - effect: NoSchedule
          key: workload
          value: tasks
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
```
2. Ensure no nodes are created in this nodepool:
```sh
> kubectl get nodes -l karpenter.sh/nodepool=tasks-nodepool
No resources found
```
3. Check to see the status of the nodepool, and ensure an empty object is returned.
```sh
> kubectl get nodepool/tasks-nodepool -o json | jq .status
{}
```
4. Check the metrics endpoint (`karpenter.karpenter.svc.cluster.local:8000/metrics`) and ensure the `karpenter_nodepool_usage` gauge metric does not include data for the `tasks-nodepool` nodepool. 

**Versions**:
- Chart Version: 0.32.4
- Kubernetes Version (`kubectl version`): v1.28.4-eks-8cb36c9

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Bryce-Soghigian** [comment]
Is it empty nodepools or new nodepools?

**Comment by mattsre** [comment]
Empty nodepools. Once nodes are created for a pool, metrics will be reported and the nodepool will have a status. When the nodes are removed due to being empty, the metrics are no longer reported and the status is gone.

**Comment by mattsre** [comment]
Quoting from my comment on a Slack [thread](https://kubernetes.slack.com/archives/C02SFFZSA2K/p1705073602592799)

> Looking at the metrics code, the root cause is likely the nodepool status not containing resources when no nodes are in the pool. Seems the resourceCountsFor method responsible for setting the resources status doesn't handle the case when there are no nodes owned by this nodepool. https://github.com/kubernetes-sigs/karpenter/blob/v0.32.4/pkg/controllers/nodepool/counter/controller.go#L77-L94

**Comment by jonathan-innis** [comment]
This makes sense to me. One solve that fixes the status that's returned in the NodePool and what's returned by the usage metric. We should note that this is a breaking change, though (I doubt there is a large base of users that are relying on the empty resource status behavior, but it's something that we should callout when we make the change).

**Comment by jonathan-innis** [comment]
@mattsre Any chance you would be willing to open a PR with the fix?

**Comment by mattsre** [comment]
@jonathan-innis I took a crack at this in #940
While making the PR I noticed there was a test that explicitly ensured the resources status was nil, figured I'd mention in case you knew of some reason this _needs_ to nil when there are 0 nodes that I'm not aware of.

**Comment by ellistarn** [comment]
> @jonathan-innis I took a crack at this in #940 While making the PR I noticed there was a test that explicitly ensured the resources status was nil, figured I'd mention in case you knew of some reason this _needs_ to nil when there are 0 nodes that I'm not aware of.

I'm not aware of any. It's possible that we just wrote the test against the behavior ;)

**Comment by njtran** [comment]
I'm seeing that the resources are 0 on my NodePool. Closing this out as solved
```
    resources:
      cpu: "0"
      ephemeral-storage: "0"
      memory: "0"
      nodes: "0"
      pods: "0"
```
